// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: gate/gate_ss.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家
type CNoticePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNoticePlayer) Reset() {
	*x = CNoticePlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNoticePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNoticePlayer) ProtoMessage() {}

func (x *CNoticePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNoticePlayer.ProtoReflect.Descriptor instead.
func (*CNoticePlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{0}
}

func (x *CNoticePlayer) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SNoticePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNoticePlayer) Reset() {
	*x = SNoticePlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNoticePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticePlayer) ProtoMessage() {}

func (x *SNoticePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticePlayer.ProtoReflect.Descriptor instead.
func (*SNoticePlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{1}
}

func (x *SNoticePlayer) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_gate_gate_ss_proto protoreflect.FileDescriptor

const file_gate_gate_ss_proto_rawDesc = "" +
	"\n" +
	"\x12gate/gate_ss.proto\x12\x04gate\",\n" +
	"\rCNoticePlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\")\n" +
	"\rSNoticePlayer\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontentBCZ6github.com/fixkme/protoc-gen-gom/example/pbout/go/gate\xaa\x02\bProtocolb\x06proto3"

var (
	file_gate_gate_ss_proto_rawDescOnce sync.Once
	file_gate_gate_ss_proto_rawDescData []byte
)

func file_gate_gate_ss_proto_rawDescGZIP() []byte {
	file_gate_gate_ss_proto_rawDescOnce.Do(func() {
		file_gate_gate_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_gate_ss_proto_rawDesc), len(file_gate_gate_ss_proto_rawDesc)))
	})
	return file_gate_gate_ss_proto_rawDescData
}

var file_gate_gate_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gate_gate_ss_proto_goTypes = []any{
	(*CNoticePlayer)(nil), // 0: gate.CNoticePlayer
	(*SNoticePlayer)(nil), // 1: gate.SNoticePlayer
}
var file_gate_gate_ss_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gate_gate_ss_proto_init() }
func file_gate_gate_ss_proto_init() {
	if File_gate_gate_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_gate_ss_proto_rawDesc), len(file_gate_gate_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_gate_ss_proto_goTypes,
		DependencyIndexes: file_gate_gate_ss_proto_depIdxs,
		MessageInfos:      file_gate_gate_ss_proto_msgTypes,
	}.Build()
	File_gate_gate_ss_proto = out.File
	file_gate_gate_ss_proto_goTypes = nil
	file_gate_gate_ss_proto_depIdxs = nil
}
