// Code generated by protoc-gen-gom. DO NOT EDIT.
package gate

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type GateServer interface {
	NoticePlayer(context.Context, *CNoticePlayer) (*SNoticePlayer, error)
}

func RegisterGateServer(s rpc.ServiceRegistrar, srv GateServer) {
	s.RegisterService(&Gate_ServiceDesc, srv)
}

func _Gate_NoticePlayer_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CNoticePlayer)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GateServer).NoticePlayer(ctx, req.(*CNoticePlayer))
	}
	return arg, h
}

var Gate_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "NoticePlayer",
			Handler:    _Gate_NoticePlayer_Materializer,
		},
	},
}
