// Code generated by protoc-gen-gom. DO NOT EDIT.
package gate

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type GateServer interface {
	NoticePlayer(context.Context, *CNoticePlayer) (*SNoticePlayer, error)
}

func RegisterGateServer(s rpc.ServiceRegistrar, srv GateServer) {
	s.RegisterService(&Gate_ServiceDesc, srv)
}

func _Gate_NoticePlayer_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CNoticePlayer)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GateServer).NoticePlayer(ctx, req)
}

var Gate_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "NoticePlayer",
			Handler:    _Gate_NoticePlayer_Handler,
		},
	},
}
