// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.1
// source: game/activity.proto

package game

import (
	datas "github.com/protoc-gen-gom/example/pbout/go/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加活动
type CGameUpdateActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *datas.PBActivityData `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CGameUpdateActivity) Reset() {
	*x = CGameUpdateActivity{}
	mi := &file_game_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGameUpdateActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGameUpdateActivity) ProtoMessage() {}

func (x *CGameUpdateActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGameUpdateActivity.ProtoReflect.Descriptor instead.
func (*CGameUpdateActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_proto_rawDescGZIP(), []int{0}
}

func (x *CGameUpdateActivity) GetInfo() *datas.PBActivityData {
	if x != nil {
		return x.Info
	}
	return nil
}

type SGameUpdateActivity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SGameUpdateActivity) Reset() {
	*x = SGameUpdateActivity{}
	mi := &file_game_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGameUpdateActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGameUpdateActivity) ProtoMessage() {}

func (x *SGameUpdateActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGameUpdateActivity.ProtoReflect.Descriptor instead.
func (*SGameUpdateActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_proto_rawDescGZIP(), []int{1}
}

var File_game_activity_proto protoreflect.FileDescriptor

var file_game_activity_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x19, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x13, 0x43, 0x47, 0x61, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x27, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x47, 0x61, 0x6d, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x42, 0x3c, 0x5a,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0xaa, 0x02, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_game_activity_proto_rawDescOnce sync.Once
	file_game_activity_proto_rawDescData = file_game_activity_proto_rawDesc
)

func file_game_activity_proto_rawDescGZIP() []byte {
	file_game_activity_proto_rawDescOnce.Do(func() {
		file_game_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_activity_proto_rawDescData)
	})
	return file_game_activity_proto_rawDescData
}

var file_game_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_activity_proto_goTypes = []any{
	(*CGameUpdateActivity)(nil),  // 0: game.CGameUpdateActivity
	(*SGameUpdateActivity)(nil),  // 1: game.SGameUpdateActivity
	(*datas.PBActivityData)(nil), // 2: datas.ActivityData
}
var file_game_activity_proto_depIdxs = []int32{
	2, // 0: game.CGameUpdateActivity.info:type_name -> datas.ActivityData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_activity_proto_init() }
func file_game_activity_proto_init() {
	if File_game_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_activity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_activity_proto_goTypes,
		DependencyIndexes: file_game_activity_proto_depIdxs,
		MessageInfos:      file_game_activity_proto_msgTypes,
	}.Build()
	File_game_activity_proto = out.File
	file_game_activity_proto_rawDesc = nil
	file_game_activity_proto_goTypes = nil
	file_game_activity_proto_depIdxs = nil
}
