// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: game/activity.proto

package game

import (
	datas "github.com/fixkme/protoc-gen-gom/example/pbout/go/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 拉取活动列表
type CGetActivityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CGetActivityList) Reset() {
	*x = CGetActivityList{}
	mi := &file_game_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGetActivityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGetActivityList) ProtoMessage() {}

func (x *CGetActivityList) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGetActivityList.ProtoReflect.Descriptor instead.
func (*CGetActivityList) Descriptor() ([]byte, []int) {
	return file_game_activity_proto_rawDescGZIP(), []int{0}
}

type SGetActivityList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Infos         []*datas.PBActivityInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGetActivityList) Reset() {
	*x = SGetActivityList{}
	mi := &file_game_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGetActivityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGetActivityList) ProtoMessage() {}

func (x *SGetActivityList) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGetActivityList.ProtoReflect.Descriptor instead.
func (*SGetActivityList) Descriptor() ([]byte, []int) {
	return file_game_activity_proto_rawDescGZIP(), []int{1}
}

func (x *SGetActivityList) GetInfos() []*datas.PBActivityInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_game_activity_proto protoreflect.FileDescriptor

const file_game_activity_proto_rawDesc = "" +
	"\n" +
	"\x13game/activity.proto\x12\x04game\x1a\x19datas/activity_data.proto\"\x12\n" +
	"\x10CGetActivityList\"=\n" +
	"\x10SGetActivityList\x12)\n" +
	"\x05infos\x18\x01 \x03(\v2\x13.datas.ActivityInfoR\x05infosBCZ6github.com/fixkme/protoc-gen-gom/example/pbout/go/game\xaa\x02\bProtocolb\x06proto3"

var (
	file_game_activity_proto_rawDescOnce sync.Once
	file_game_activity_proto_rawDescData []byte
)

func file_game_activity_proto_rawDescGZIP() []byte {
	file_game_activity_proto_rawDescOnce.Do(func() {
		file_game_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_activity_proto_rawDesc), len(file_game_activity_proto_rawDesc)))
	})
	return file_game_activity_proto_rawDescData
}

var file_game_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_activity_proto_goTypes = []any{
	(*CGetActivityList)(nil),     // 0: game.CGetActivityList
	(*SGetActivityList)(nil),     // 1: game.SGetActivityList
	(*datas.PBActivityInfo)(nil), // 2: datas.ActivityInfo
}
var file_game_activity_proto_depIdxs = []int32{
	2, // 0: game.SGetActivityList.infos:type_name -> datas.ActivityInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_activity_proto_init() }
func file_game_activity_proto_init() {
	if File_game_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_activity_proto_rawDesc), len(file_game_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_activity_proto_goTypes,
		DependencyIndexes: file_game_activity_proto_depIdxs,
		MessageInfos:      file_game_activity_proto_msgTypes,
	}.Build()
	File_game_activity_proto = out.File
	file_game_activity_proto_goTypes = nil
	file_game_activity_proto_depIdxs = nil
}
