// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: game/activity_ss.proto

package game

import (
	datas "github.com/fixkme/protoc-gen-gom/example/pbout/go/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加活动
type CGameAddActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *datas.PBActivityData  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CGameAddActivity) Reset() {
	*x = CGameAddActivity{}
	mi := &file_game_activity_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGameAddActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGameAddActivity) ProtoMessage() {}

func (x *CGameAddActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGameAddActivity.ProtoReflect.Descriptor instead.
func (*CGameAddActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{0}
}

func (x *CGameAddActivity) GetInfo() *datas.PBActivityData {
	if x != nil {
		return x.Info
	}
	return nil
}

type SGameAddActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGameAddActivity) Reset() {
	*x = SGameAddActivity{}
	mi := &file_game_activity_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGameAddActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGameAddActivity) ProtoMessage() {}

func (x *SGameAddActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGameAddActivity.ProtoReflect.Descriptor instead.
func (*SGameAddActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{1}
}

// 更新活动
type CGameUpdateActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *datas.PBActivityData  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CGameUpdateActivity) Reset() {
	*x = CGameUpdateActivity{}
	mi := &file_game_activity_ss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGameUpdateActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGameUpdateActivity) ProtoMessage() {}

func (x *CGameUpdateActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGameUpdateActivity.ProtoReflect.Descriptor instead.
func (*CGameUpdateActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{2}
}

func (x *CGameUpdateActivity) GetInfo() *datas.PBActivityData {
	if x != nil {
		return x.Info
	}
	return nil
}

type SGameUpdateActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGameUpdateActivity) Reset() {
	*x = SGameUpdateActivity{}
	mi := &file_game_activity_ss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGameUpdateActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGameUpdateActivity) ProtoMessage() {}

func (x *SGameUpdateActivity) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGameUpdateActivity.ProtoReflect.Descriptor instead.
func (*SGameUpdateActivity) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{3}
}

// 更新活动状态
type CGameUpdateActivityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        datas.ActivityStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=datas.ActivityStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CGameUpdateActivityStatus) Reset() {
	*x = CGameUpdateActivityStatus{}
	mi := &file_game_activity_ss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGameUpdateActivityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGameUpdateActivityStatus) ProtoMessage() {}

func (x *CGameUpdateActivityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGameUpdateActivityStatus.ProtoReflect.Descriptor instead.
func (*CGameUpdateActivityStatus) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{4}
}

func (x *CGameUpdateActivityStatus) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CGameUpdateActivityStatus) GetStatus() datas.ActivityStatus {
	if x != nil {
		return x.Status
	}
	return datas.ActivityStatus(0)
}

type SGameUpdateActivityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGameUpdateActivityStatus) Reset() {
	*x = SGameUpdateActivityStatus{}
	mi := &file_game_activity_ss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGameUpdateActivityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGameUpdateActivityStatus) ProtoMessage() {}

func (x *SGameUpdateActivityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_game_activity_ss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGameUpdateActivityStatus.ProtoReflect.Descriptor instead.
func (*SGameUpdateActivityStatus) Descriptor() ([]byte, []int) {
	return file_game_activity_ss_proto_rawDescGZIP(), []int{5}
}

var File_game_activity_ss_proto protoreflect.FileDescriptor

const file_game_activity_ss_proto_rawDesc = "" +
	"\n" +
	"\x16game/activity_ss.proto\x12\x04game\x1a\x19datas/activity_data.proto\x1a\x1cdatas/activity_data_ss.proto\";\n" +
	"\x10CGameAddActivity\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.datas.ActivityDataR\x04info\"\x12\n" +
	"\x10SGameAddActivity\">\n" +
	"\x13CGameUpdateActivity\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.datas.ActivityDataR\x04info\"\x15\n" +
	"\x13SGameUpdateActivity\"Z\n" +
	"\x19CGameUpdateActivityStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.datas.ActivityStatusR\x06status\"\x1b\n" +
	"\x19SGameUpdateActivityStatusBCZ6github.com/fixkme/protoc-gen-gom/example/pbout/go/game\xaa\x02\bProtocolb\x06proto3"

var (
	file_game_activity_ss_proto_rawDescOnce sync.Once
	file_game_activity_ss_proto_rawDescData []byte
)

func file_game_activity_ss_proto_rawDescGZIP() []byte {
	file_game_activity_ss_proto_rawDescOnce.Do(func() {
		file_game_activity_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_activity_ss_proto_rawDesc), len(file_game_activity_ss_proto_rawDesc)))
	})
	return file_game_activity_ss_proto_rawDescData
}

var file_game_activity_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_activity_ss_proto_goTypes = []any{
	(*CGameAddActivity)(nil),          // 0: game.CGameAddActivity
	(*SGameAddActivity)(nil),          // 1: game.SGameAddActivity
	(*CGameUpdateActivity)(nil),       // 2: game.CGameUpdateActivity
	(*SGameUpdateActivity)(nil),       // 3: game.SGameUpdateActivity
	(*CGameUpdateActivityStatus)(nil), // 4: game.CGameUpdateActivityStatus
	(*SGameUpdateActivityStatus)(nil), // 5: game.SGameUpdateActivityStatus
	(*datas.PBActivityData)(nil),      // 6: datas.ActivityData
	(datas.ActivityStatus)(0),         // 7: datas.ActivityStatus
}
var file_game_activity_ss_proto_depIdxs = []int32{
	6, // 0: game.CGameAddActivity.info:type_name -> datas.ActivityData
	6, // 1: game.CGameUpdateActivity.info:type_name -> datas.ActivityData
	7, // 2: game.CGameUpdateActivityStatus.status:type_name -> datas.ActivityStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_game_activity_ss_proto_init() }
func file_game_activity_ss_proto_init() {
	if File_game_activity_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_activity_ss_proto_rawDesc), len(file_game_activity_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_activity_ss_proto_goTypes,
		DependencyIndexes: file_game_activity_ss_proto_depIdxs,
		MessageInfos:      file_game_activity_ss_proto_msgTypes,
	}.Build()
	File_game_activity_ss_proto = out.File
	file_game_activity_ss_proto_goTypes = nil
	file_game_activity_ss_proto_depIdxs = nil
}
