// Code generated by protoc-gen-gom. DO NOT EDIT.
package game

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type GameServer interface {
	GameAddActivity(context.Context, *CGameAddActivity) (*SGameAddActivity, error)
	GameUpdateActivity(context.Context, *CGameUpdateActivity) (*SGameUpdateActivity, error)
	GameUpdateActivityStatus(context.Context, *CGameUpdateActivityStatus) (*SGameUpdateActivityStatus, error)
	GetActivityList(context.Context, *CGetActivityList) (*SGetActivityList, error)
	LoginGame(context.Context, *CLoginGame) (*SLoginGame, error)
}

func RegisterGameServer(s rpc.ServiceRegistrar, srv GameServer) {
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_GameAddActivity_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CGameAddActivity)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).GameAddActivity(ctx, req.(*CGameAddActivity))
	}
	return arg, h
}

func _Game_GameUpdateActivity_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CGameUpdateActivity)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).GameUpdateActivity(ctx, req.(*CGameUpdateActivity))
	}
	return arg, h
}

func _Game_GameUpdateActivityStatus_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CGameUpdateActivityStatus)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).GameUpdateActivityStatus(ctx, req.(*CGameUpdateActivityStatus))
	}
	return arg, h
}

func _Game_GetActivityList_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CGetActivityList)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).GetActivityList(ctx, req.(*CGetActivityList))
	}
	return arg, h
}

func _Game_LoginGame_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CLoginGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).LoginGame(ctx, req.(*CLoginGame))
	}
	return arg, h
}

var Game_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "game",
	HandlerType: (*GameServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "GameAddActivity",
			Handler:    _Game_GameAddActivity_Materializer,
		},
		{
			MethodName: "GameUpdateActivity",
			Handler:    _Game_GameUpdateActivity_Materializer,
		},
		{
			MethodName: "GameUpdateActivityStatus",
			Handler:    _Game_GameUpdateActivityStatus_Materializer,
		},
		{
			MethodName: "GetActivityList",
			Handler:    _Game_GetActivityList_Materializer,
		},
		{
			MethodName: "LoginGame",
			Handler:    _Game_LoginGame_Materializer,
		},
	},
}
