// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: game/game.grpc.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_game_game_grpc_proto protoreflect.FileDescriptor

const file_game_game_grpc_proto_rawDesc = "" +
	"\n" +
	"\x14game/game.grpc.proto\x12\x04game\x1a\x10game/login.proto\x1a\x13game/activity.proto2{\n" +
	"\x05MGame\x12/\n" +
	"\tLoginGame\x12\x10.game.CLoginGame\x1a\x10.game.SLoginGame\x12A\n" +
	"\x0fGetActivityList\x12\x16.game.CGetActivityList\x1a\x16.game.SGetActivityListB8Z6github.com/fixkme/protoc-gen-gom/example/pbout/go/gameb\x06proto3"

var file_game_game_grpc_proto_goTypes = []any{
	(*CLoginGame)(nil),       // 0: game.CLoginGame
	(*CGetActivityList)(nil), // 1: game.CGetActivityList
	(*SLoginGame)(nil),       // 2: game.SLoginGame
	(*SGetActivityList)(nil), // 3: game.SGetActivityList
}
var file_game_game_grpc_proto_depIdxs = []int32{
	0, // 0: game.MGame.LoginGame:input_type -> game.CLoginGame
	1, // 1: game.MGame.GetActivityList:input_type -> game.CGetActivityList
	2, // 2: game.MGame.LoginGame:output_type -> game.SLoginGame
	3, // 3: game.MGame.GetActivityList:output_type -> game.SGetActivityList
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_game_grpc_proto_init() }
func file_game_game_grpc_proto_init() {
	if File_game_game_grpc_proto != nil {
		return
	}
	file_game_login_proto_init()
	file_game_activity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_game_grpc_proto_rawDesc), len(file_game_game_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_game_grpc_proto_goTypes,
		DependencyIndexes: file_game_game_grpc_proto_depIdxs,
	}.Build()
	File_game_game_grpc_proto = out.File
	file_game_game_grpc_proto_goTypes = nil
	file_game_game_grpc_proto_depIdxs = nil
}
