// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: game/game.grpc.proto

package game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MGame_LoginGame_FullMethodName       = "/game.MGame/LoginGame"
	MGame_GetActivityList_FullMethodName = "/game.MGame/GetActivityList"
)

// MGameClient is the client API for MGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MGameClient interface {
	LoginGame(ctx context.Context, in *CLoginGame, opts ...grpc.CallOption) (*SLoginGame, error)
	GetActivityList(ctx context.Context, in *CGetActivityList, opts ...grpc.CallOption) (*SGetActivityList, error)
}

type mGameClient struct {
	cc grpc.ClientConnInterface
}

func NewMGameClient(cc grpc.ClientConnInterface) MGameClient {
	return &mGameClient{cc}
}

func (c *mGameClient) LoginGame(ctx context.Context, in *CLoginGame, opts ...grpc.CallOption) (*SLoginGame, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SLoginGame)
	err := c.cc.Invoke(ctx, MGame_LoginGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mGameClient) GetActivityList(ctx context.Context, in *CGetActivityList, opts ...grpc.CallOption) (*SGetActivityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SGetActivityList)
	err := c.cc.Invoke(ctx, MGame_GetActivityList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MGameServer is the server API for MGame service.
// All implementations must embed UnimplementedMGameServer
// for forward compatibility.
type MGameServer interface {
	LoginGame(context.Context, *CLoginGame) (*SLoginGame, error)
	GetActivityList(context.Context, *CGetActivityList) (*SGetActivityList, error)
	mustEmbedUnimplementedMGameServer()
}

// UnimplementedMGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMGameServer struct{}

func (UnimplementedMGameServer) LoginGame(context.Context, *CLoginGame) (*SLoginGame, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginGame not implemented")
}
func (UnimplementedMGameServer) GetActivityList(context.Context, *CGetActivityList) (*SGetActivityList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityList not implemented")
}
func (UnimplementedMGameServer) mustEmbedUnimplementedMGameServer() {}
func (UnimplementedMGameServer) testEmbeddedByValue()               {}

// UnsafeMGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MGameServer will
// result in compilation errors.
type UnsafeMGameServer interface {
	mustEmbedUnimplementedMGameServer()
}

func RegisterMGameServer(s grpc.ServiceRegistrar, srv MGameServer) {
	// If the following call pancis, it indicates UnimplementedMGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MGame_ServiceDesc, srv)
}

func _MGame_LoginGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CLoginGame)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MGameServer).LoginGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MGame_LoginGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MGameServer).LoginGame(ctx, req.(*CLoginGame))
	}
	return interceptor(ctx, in, info, handler)
}

func _MGame_GetActivityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CGetActivityList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MGameServer).GetActivityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MGame_GetActivityList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MGameServer).GetActivityList(ctx, req.(*CGetActivityList))
	}
	return interceptor(ctx, in, info, handler)
}

// MGame_ServiceDesc is the grpc.ServiceDesc for MGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.MGame",
	HandlerType: (*MGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginGame",
			Handler:    _MGame_LoginGame_Handler,
		},
		{
			MethodName: "GetActivityList",
			Handler:    _MGame_GetActivityList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game/game.grpc.proto",
}
