// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: game/game_ss.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPlayerOffline) Reset() {
	*x = CPlayerOffline{}
	mi := &file_game_game_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPlayerOffline) ProtoMessage() {}

func (x *CPlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPlayerOffline.ProtoReflect.Descriptor instead.
func (*CPlayerOffline) Descriptor() ([]byte, []int) {
	return file_game_game_ss_proto_rawDescGZIP(), []int{0}
}

func (x *CPlayerOffline) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SPlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPlayerOffline) Reset() {
	*x = SPlayerOffline{}
	mi := &file_game_game_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPlayerOffline) ProtoMessage() {}

func (x *SPlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPlayerOffline.ProtoReflect.Descriptor instead.
func (*SPlayerOffline) Descriptor() ([]byte, []int) {
	return file_game_game_ss_proto_rawDescGZIP(), []int{1}
}

var File_game_game_ss_proto protoreflect.FileDescriptor

const file_game_game_ss_proto_rawDesc = "" +
	"\n" +
	"\x12game/game_ss.proto\x12\x04game\"-\n" +
	"\x0eCPlayerOffline\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x10\n" +
	"\x0eSPlayerOfflineBCZ6github.com/fixkme/protoc-gen-gom/example/pbout/go/game\xaa\x02\bProtocolb\x06proto3"

var (
	file_game_game_ss_proto_rawDescOnce sync.Once
	file_game_game_ss_proto_rawDescData []byte
)

func file_game_game_ss_proto_rawDescGZIP() []byte {
	file_game_game_ss_proto_rawDescOnce.Do(func() {
		file_game_game_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_game_ss_proto_rawDesc), len(file_game_game_ss_proto_rawDesc)))
	})
	return file_game_game_ss_proto_rawDescData
}

var file_game_game_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_game_ss_proto_goTypes = []any{
	(*CPlayerOffline)(nil), // 0: game.CPlayerOffline
	(*SPlayerOffline)(nil), // 1: game.SPlayerOffline
}
var file_game_game_ss_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_game_ss_proto_init() }
func file_game_game_ss_proto_init() {
	if File_game_game_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_game_ss_proto_rawDesc), len(file_game_game_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_game_ss_proto_goTypes,
		DependencyIndexes: file_game_game_ss_proto_depIdxs,
		MessageInfos:      file_game_game_ss_proto_msgTypes,
	}.Build()
	File_game_game_ss_proto = out.File
	file_game_game_ss_proto_goTypes = nil
	file_game_game_ss_proto_depIdxs = nil
}
