// Code generated by protoc-gen-gom. DO NOT EDIT.
package game

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type GameServer interface {
	GameAddActivity(context.Context, *CGameAddActivity) (*SGameAddActivity, error)
	GameUpdateActivity(context.Context, *CGameUpdateActivity) (*SGameUpdateActivity, error)
	GameUpdateActivityStatus(context.Context, *CGameUpdateActivityStatus) (*SGameUpdateActivityStatus, error)
	GetActivityList(context.Context, *CGetActivityList) (*SGetActivityList, error)
	LoginGame(context.Context, *CLoginGame) (*SLoginGame, error)
}

func _Game_GameAddActivity_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CGameAddActivity)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GameServer).GameAddActivity(ctx, req)
}

func _Game_GameUpdateActivity_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CGameUpdateActivity)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GameServer).GameUpdateActivity(ctx, req)
}

func _Game_GameUpdateActivityStatus_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CGameUpdateActivityStatus)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GameServer).GameUpdateActivityStatus(ctx, req)
}

func _Game_GetActivityList_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CGetActivityList)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GameServer).GetActivityList(ctx, req)
}

func _Game_LoginGame_Handler(srv any, ctx context.Context, in []byte) (proto.Message, error) {
	req := new(CLoginGame)
	if err := proto.Unmarshal(in, req); err != nil {
		return nil, err
	}
	return srv.(GameServer).LoginGame(ctx, req)
}

var Game_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "Game",
	HandlerType: (*GameServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "GameAddActivity",
			Handler:    _Game_GameAddActivity_Handler,
		},
		{
			MethodName: "GameUpdateActivity",
			Handler:    _Game_GameUpdateActivity_Handler,
		},
		{
			MethodName: "GameUpdateActivityStatus",
			Handler:    _Game_GameUpdateActivityStatus_Handler,
		},
		{
			MethodName: "GetActivityList",
			Handler:    _Game_GetActivityList_Handler,
		},
		{
			MethodName: "LoginGame",
			Handler:    _Game_LoginGame_Handler,
		},
	},
}
