// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.1
// source: game/login.proto

package game

import (
	model "github.com/protoc-gen-gom/example/pbout/go/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 拉取活动列表
type CLoginGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CLoginGame) Reset() {
	*x = CLoginGame{}
	mi := &file_game_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLoginGame) ProtoMessage() {}

func (x *CLoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLoginGame.ProtoReflect.Descriptor instead.
func (*CLoginGame) Descriptor() ([]byte, []int) {
	return file_game_login_proto_rawDescGZIP(), []int{0}
}

type SLoginGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerModel    *model.PBPlayerModel `protobuf:"bytes,1,opt,name=player_model,json=playerModel,proto3" json:"player_model,omitempty"`
	TimezoneOffset int64                `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"` //服务器时区，utc偏移秒数
	ServerTime     int64                `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`             //服务器时间
}

func (x *SLoginGame) Reset() {
	*x = SLoginGame{}
	mi := &file_game_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLoginGame) ProtoMessage() {}

func (x *SLoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLoginGame.ProtoReflect.Descriptor instead.
func (*SLoginGame) Descriptor() ([]byte, []int) {
	return file_game_login_proto_rawDescGZIP(), []int{1}
}

func (x *SLoginGame) GetPlayerModel() *model.PBPlayerModel {
	if x != nil {
		return x.PlayerModel
	}
	return nil
}

func (x *SLoginGame) GetTimezoneOffset() int64 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *SLoginGame) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_game_login_proto protoreflect.FileDescriptor

var file_game_login_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x1a, 0x18, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x22, 0x8d, 0x01, 0x0a, 0x0a, 0x53, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f,
	0x6e, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x74, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x42, 0x3c, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x6d, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x6f, 0x75, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0xaa, 0x02, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_login_proto_rawDescOnce sync.Once
	file_game_login_proto_rawDescData = file_game_login_proto_rawDesc
)

func file_game_login_proto_rawDescGZIP() []byte {
	file_game_login_proto_rawDescOnce.Do(func() {
		file_game_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_login_proto_rawDescData)
	})
	return file_game_login_proto_rawDescData
}

var file_game_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_login_proto_goTypes = []any{
	(*CLoginGame)(nil),          // 0: game.CLoginGame
	(*SLoginGame)(nil),          // 1: game.SLoginGame
	(*model.PBPlayerModel)(nil), // 2: model.PlayerModel
}
var file_game_login_proto_depIdxs = []int32{
	2, // 0: game.SLoginGame.player_model:type_name -> model.PlayerModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_login_proto_init() }
func file_game_login_proto_init() {
	if File_game_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_login_proto_goTypes,
		DependencyIndexes: file_game_login_proto_depIdxs,
		MessageInfos:      file_game_login_proto_msgTypes,
	}.Build()
	File_game_login_proto = out.File
	file_game_login_proto_rawDesc = nil
	file_game_login_proto_goTypes = nil
	file_game_login_proto_depIdxs = nil
}
