// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: game/login.proto

package game

import (
	model "github.com/fixkme/protoc-gen-gom/example/pbout/go/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 拉取活动列表
type CLoginGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLoginGame) Reset() {
	*x = CLoginGame{}
	mi := &file_game_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLoginGame) ProtoMessage() {}

func (x *CLoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLoginGame.ProtoReflect.Descriptor instead.
func (*CLoginGame) Descriptor() ([]byte, []int) {
	return file_game_login_proto_rawDescGZIP(), []int{0}
}

type SLoginGame struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerModel    *model.PBPlayerModel   `protobuf:"bytes,1,opt,name=player_model,json=playerModel,proto3" json:"player_model,omitempty"`
	TimezoneOffset int64                  `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"` //服务器时区，utc偏移秒数
	ServerTime     int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`             //服务器时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SLoginGame) Reset() {
	*x = SLoginGame{}
	mi := &file_game_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLoginGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLoginGame) ProtoMessage() {}

func (x *SLoginGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLoginGame.ProtoReflect.Descriptor instead.
func (*SLoginGame) Descriptor() ([]byte, []int) {
	return file_game_login_proto_rawDescGZIP(), []int{1}
}

func (x *SLoginGame) GetPlayerModel() *model.PBPlayerModel {
	if x != nil {
		return x.PlayerModel
	}
	return nil
}

func (x *SLoginGame) GetTimezoneOffset() int64 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *SLoginGame) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_game_login_proto protoreflect.FileDescriptor

const file_game_login_proto_rawDesc = "" +
	"\n" +
	"\x10game/login.proto\x12\x04game\x1a\x18model/player_model.proto\"\f\n" +
	"\n" +
	"CLoginGame\"\x8d\x01\n" +
	"\n" +
	"SLoginGame\x125\n" +
	"\fplayer_model\x18\x01 \x01(\v2\x12.model.PlayerModelR\vplayerModel\x12'\n" +
	"\x0ftimezone_offset\x18\x02 \x01(\x03R\x0etimezoneOffset\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTimeBCZ6github.com/fixkme/protoc-gen-gom/example/pbout/go/game\xaa\x02\bProtocolb\x06proto3"

var (
	file_game_login_proto_rawDescOnce sync.Once
	file_game_login_proto_rawDescData []byte
)

func file_game_login_proto_rawDescGZIP() []byte {
	file_game_login_proto_rawDescOnce.Do(func() {
		file_game_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_login_proto_rawDesc), len(file_game_login_proto_rawDesc)))
	})
	return file_game_login_proto_rawDescData
}

var file_game_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_login_proto_goTypes = []any{
	(*CLoginGame)(nil),          // 0: game.CLoginGame
	(*SLoginGame)(nil),          // 1: game.SLoginGame
	(*model.PBPlayerModel)(nil), // 2: model.PlayerModel
}
var file_game_login_proto_depIdxs = []int32{
	2, // 0: game.SLoginGame.player_model:type_name -> model.PlayerModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_login_proto_init() }
func file_game_login_proto_init() {
	if File_game_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_login_proto_rawDesc), len(file_game_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_login_proto_goTypes,
		DependencyIndexes: file_game_login_proto_depIdxs,
		MessageInfos:      file_game_login_proto_msgTypes,
	}.Build()
	File_game_login_proto = out.File
	file_game_login_proto_goTypes = nil
	file_game_login_proto_depIdxs = nil
}
