// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: model/model_activity.proto

package model

import (
	datas "github.com/fixkme/protoc-gen-gom/example/pbout/go/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBSawingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 冲榜活动轮次
	SawingRound int64 `protobuf:"varint,1,opt,name=sawing_round,json=sawingRound,proto3" json:"sawing_round,omitempty"`
	// 冲榜活动轮次阶段
	SawingStep    int64                `protobuf:"varint,2,opt,name=sawing_step,json=sawingStep,proto3" json:"sawing_step,omitempty"`
	Status        datas.ActivityStatus `protobuf:"varint,3,opt,name=status,proto3,enum=datas.ActivityStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSawingInfo) Reset() {
	*x = PBSawingInfo{}
	mi := &file_model_model_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSawingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSawingInfo) ProtoMessage() {}

func (x *PBSawingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_model_model_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSawingInfo.ProtoReflect.Descriptor instead.
func (*PBSawingInfo) Descriptor() ([]byte, []int) {
	return file_model_model_activity_proto_rawDescGZIP(), []int{0}
}

func (x *PBSawingInfo) GetSawingRound() int64 {
	if x != nil {
		return x.SawingRound
	}
	return 0
}

func (x *PBSawingInfo) GetSawingStep() int64 {
	if x != nil {
		return x.SawingStep
	}
	return 0
}

func (x *PBSawingInfo) GetStatus() datas.ActivityStatus {
	if x != nil {
		return x.Status
	}
	return datas.ActivityStatus(0)
}

// 玩家活动数据
type PBModelActivity struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalActivityIds map[int32]int32        `protobuf:"bytes,1,rep,name=local_activity_ids,json=localActivityIds,proto3" json:"local_activity_ids,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 限时累计充值活动 活动id => TimeLimitTotalRechargeInfo
	TotalRecharges map[int64]*datas.PBTimeLimitTotalRechargeInfo `protobuf:"bytes,2,rep,name=total_recharges,json=totalRecharges,proto3" json:"total_recharges,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 累计金额、天数
	// 冲榜活动信息
	SawingData    *PBSawingInfo `protobuf:"bytes,3,opt,name=sawing_data,json=sawingData,proto3" json:"sawing_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBModelActivity) Reset() {
	*x = PBModelActivity{}
	mi := &file_model_model_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBModelActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBModelActivity) ProtoMessage() {}

func (x *PBModelActivity) ProtoReflect() protoreflect.Message {
	mi := &file_model_model_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBModelActivity.ProtoReflect.Descriptor instead.
func (*PBModelActivity) Descriptor() ([]byte, []int) {
	return file_model_model_activity_proto_rawDescGZIP(), []int{1}
}

func (x *PBModelActivity) GetLocalActivityIds() map[int32]int32 {
	if x != nil {
		return x.LocalActivityIds
	}
	return nil
}

func (x *PBModelActivity) GetTotalRecharges() map[int64]*datas.PBTimeLimitTotalRechargeInfo {
	if x != nil {
		return x.TotalRecharges
	}
	return nil
}

func (x *PBModelActivity) GetSawingData() *PBSawingInfo {
	if x != nil {
		return x.SawingData
	}
	return nil
}

var File_model_model_activity_proto protoreflect.FileDescriptor

const file_model_model_activity_proto_rawDesc = "" +
	"\n" +
	"\x1amodel/model_activity.proto\x12\x05model\x1a\x19datas/activity_data.proto\"\x7f\n" +
	"\n" +
	"SawingInfo\x12!\n" +
	"\fsawing_round\x18\x01 \x01(\x03R\vsawingRound\x12\x1f\n" +
	"\vsawing_step\x18\x02 \x01(\x03R\n" +
	"sawingStep\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.datas.ActivityStatusR\x06status\"\x9b\x03\n" +
	"\rModelActivity\x12X\n" +
	"\x12local_activity_ids\x18\x01 \x03(\v2*.model.ModelActivity.LocalActivityIdsEntryR\x10localActivityIds\x12Q\n" +
	"\x0ftotal_recharges\x18\x02 \x03(\v2(.model.ModelActivity.TotalRechargesEntryR\x0etotalRecharges\x122\n" +
	"\vsawing_data\x18\x03 \x01(\v2\x11.model.SawingInfoR\n" +
	"sawingData\x1aC\n" +
	"\x15LocalActivityIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1ad\n" +
	"\x13TotalRechargesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.datas.TimeLimitTotalRechargeInfoR\x05value:\x028\x01BDZ7github.com/fixkme/protoc-gen-gom/example/pbout/go/model\xaa\x02\bProtocolb\x06proto3"

var (
	file_model_model_activity_proto_rawDescOnce sync.Once
	file_model_model_activity_proto_rawDescData []byte
)

func file_model_model_activity_proto_rawDescGZIP() []byte {
	file_model_model_activity_proto_rawDescOnce.Do(func() {
		file_model_model_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_model_activity_proto_rawDesc), len(file_model_model_activity_proto_rawDesc)))
	})
	return file_model_model_activity_proto_rawDescData
}

var file_model_model_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_model_model_activity_proto_goTypes = []any{
	(*PBSawingInfo)(nil),      // 0: model.SawingInfo
	(*PBModelActivity)(nil),   // 1: model.ModelActivity
	nil,                       // 2: model.ModelActivity.LocalActivityIdsEntry
	nil,                       // 3: model.ModelActivity.TotalRechargesEntry
	(datas.ActivityStatus)(0), // 4: datas.ActivityStatus
	(*datas.PBTimeLimitTotalRechargeInfo)(nil), // 5: datas.TimeLimitTotalRechargeInfo
}
var file_model_model_activity_proto_depIdxs = []int32{
	4, // 0: model.SawingInfo.status:type_name -> datas.ActivityStatus
	2, // 1: model.ModelActivity.local_activity_ids:type_name -> model.ModelActivity.LocalActivityIdsEntry
	3, // 2: model.ModelActivity.total_recharges:type_name -> model.ModelActivity.TotalRechargesEntry
	0, // 3: model.ModelActivity.sawing_data:type_name -> model.SawingInfo
	5, // 4: model.ModelActivity.TotalRechargesEntry.value:type_name -> datas.TimeLimitTotalRechargeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_model_model_activity_proto_init() }
func file_model_model_activity_proto_init() {
	if File_model_model_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_model_activity_proto_rawDesc), len(file_model_model_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_model_activity_proto_goTypes,
		DependencyIndexes: file_model_model_activity_proto_depIdxs,
		MessageInfos:      file_model_model_activity_proto_msgTypes,
	}.Build()
	File_model_model_activity_proto = out.File
	file_model_model_activity_proto_goTypes = nil
	file_model_model_activity_proto_depIdxs = nil
}
