// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.0.0
// 	protoc        v7.34.1
// source: model/model_activity.proto

package model

import (
	fmt "fmt"
	delta "github.com/fixkme/gokit/db/mongo/delta"
	datas "github.com/fixkme/protoc-gen-gom/example/pbout/go/datas"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// 玩家活动数据
type MModelActivity struct {
	localActivityIds map[int32]int32
	// 限时累计充值活动 活动id => TimeLimitTotalRechargeInfo
	totalRecharges map[int64]*datas.MTimeLimitTotalRechargeInfo // 累计金额、天数

	// 冲榜活动信息
	sawingData *MSawingInfo

	// 自己本身的同步key,由父对象指定
	selfSyncID string
	// 收集字典,每帧清空同步
	collector delta.ICollector
	// 监测变化回调
	changedCb func(string)
}

// 构造函数
func NewMModelActivity() *MModelActivity {
	m := &MModelActivity{}
	m.localActivityIds = make(map[int32]int32)
	m.totalRecharges = make(map[int64]*datas.MTimeLimitTotalRechargeInfo)
	m.sawingData = NewMSawingInfo()
	return m
}

// PB构造函数
func NewPBModelActivity() *PBModelActivity {
	pb := &PBModelActivity{}
	pb.LocalActivityIds = make(map[int32]int32)
	pb.TotalRecharges = make(map[int64]*datas.PBTimeLimitTotalRechargeInfo)
	pb.SawingData = NewPBSawingInfo()
	return pb
}

// 设置collector函数
func (m *MModelActivity) SetCollector(syncID string, collector delta.ICollector, cb func(string)) {
	m.collector = collector
	m.changedCb = cb
	if syncID != "" {
		syncID = syncID + "."
	}
	m.selfSyncID = syncID
	for key, value := range m.totalRecharges {
		syncKey := m.selfSyncID + "total_recharges." + strconv.FormatInt(key, 10)
		value.SetCollector(syncKey, collector, cb)
	}
	m.sawingData.SetCollector(m.selfSyncID+"sawing_data", collector, cb)
}

// 检查数值变化函数
func (m *MModelActivity) checkDirty(valueOld any, valueNew any, key string, ntfClient bool) bool {
	if reflect.DeepEqual(valueOld, valueNew) {
		return false
	}
	if m.collector != nil {
		m.collector.Collect(key, valueNew, ntfClient)
	}
	if m.changedCb != nil {
		m.changedCb(key)
	}
	return true
}

// ToPB函数
func (m *MModelActivity) ToPB() *PBModelActivity {
	if m == nil {
		return nil
	}
	pb := NewPBModelActivity()
	for key, value := range m.localActivityIds {
		pb.LocalActivityIds[key] = value
	}
	for key, value := range m.totalRecharges {
		pb.TotalRecharges[key] = value.ToPB()
	}
	pb.SawingData = m.sawingData.ToPB()
	return pb
}

// InitFromPB函数
func (m *MModelActivity) InitFromPB(pb *PBModelActivity) {
	if pb == nil {
		return
	}
	if pb.LocalActivityIds != nil {
		m.localActivityIds = pb.LocalActivityIds
	}
	for key, value := range pb.TotalRecharges {
		v := datas.NewMTimeLimitTotalRechargeInfo()
		v.InitFromPB(value)
		m.totalRecharges[key] = v
	}
	m.sawingData.InitFromPB(pb.SawingData)
}

// String 函数
func (m *MModelActivity) String() string {
	var strBuilder strings.Builder
	strBuilder.WriteString("{")
	strBuilder.WriteString("localActivityIds:")
	strBuilder.WriteString("{")
	for key, value := range m.localActivityIds {
		fmt.Fprintf(&strBuilder, "%v:%v ", key, value)
	}
	strBuilder.WriteString("}")
	strBuilder.WriteString(", ")
	strBuilder.WriteString("totalRecharges:")
	strBuilder.WriteString("{")
	for key, value := range m.totalRecharges {
		fmt.Fprintf(&strBuilder, "%v:%s ", key, value.String())
	}
	strBuilder.WriteString("}")
	strBuilder.WriteString(", ")
	strBuilder.WriteString("sawingData:")
	strBuilder.WriteString(m.sawingData.String())
	strBuilder.WriteString("}")
	return strBuilder.String()
}

func (m *MModelActivity) GetLocalActivityIds(key int32) (int32, bool) {
	value, exists := m.localActivityIds[key]
	return value, exists
}

func (m *MModelActivity) SetLocalActivityIds(key int32, value int32) {
	localSyncKey := m.selfSyncID + "local_activity_ids." + strconv.FormatInt(int64(key), 10)
	var oldValue any
	if v, ok := m.localActivityIds[key]; ok {
		oldValue = v
	} else {
		oldValue = nil
	}
	m.checkDirty(oldValue, value, localSyncKey, true)
	m.localActivityIds[key] = value
}

func (m *MModelActivity) AddLocalActivityIds(key int32, add int32) int32 {
	localSyncKey := m.selfSyncID + "local_activity_ids." + strconv.FormatInt(int64(key), 10)
	var oldValue any
	var newValue int32
	if v, ok := m.localActivityIds[key]; ok {
		oldValue, newValue = v, add+v
	} else {
		oldValue, newValue = nil, add
	}
	m.checkDirty(oldValue, newValue, localSyncKey, true)
	m.localActivityIds[key] = newValue
	return newValue
}

func (m *MModelActivity) RemoveLocalActivityIds(key int32) {
	localSyncKey := m.selfSyncID + "local_activity_ids." + strconv.FormatInt(int64(key), 10)
	m.checkDirty(m.localActivityIds[key], "__DELETE__", localSyncKey, true)
	delete(m.localActivityIds, key)
}

func (m *MModelActivity) ClearLocalActivityIds() {
	for k := range m.localActivityIds {
		m.RemoveLocalActivityIds(k)
	}
}

func (m *MModelActivity) GetLocalActivityIdsCount() int64 {
	return int64(len(m.localActivityIds))
}

func (m *MModelActivity) RangeLocalActivityIds(f func(key int32, value int32) bool) {
	for k, v := range m.localActivityIds {
		if !f(k, v) {
			return
		}
	}
}

// 限时累计充值活动 活动id => TimeLimitTotalRechargeInfo
// 累计金额、天数
func (m *MModelActivity) GetTotalRecharges(key int64) (*datas.MTimeLimitTotalRechargeInfo, bool) {
	value, exists := m.totalRecharges[key]
	return value, exists
}

func (m *MModelActivity) SetTotalRecharges(key int64, value *datas.MTimeLimitTotalRechargeInfo) {
	localSyncKey := m.selfSyncID + "total_recharges." + strconv.FormatInt(key, 10)
	var oldValue any
	if v, ok := m.totalRecharges[key]; ok {
		oldValue = v
	} else {
		oldValue = nil
	}
	if m.checkDirty(oldValue, value, localSyncKey, true) {
		value.SetCollector(localSyncKey, m.collector, m.changedCb)
	}
	m.totalRecharges[key] = value
}

func (m *MModelActivity) RemoveTotalRecharges(key int64) {
	localSyncKey := m.selfSyncID + "total_recharges." + strconv.FormatInt(key, 10)
	m.checkDirty(m.totalRecharges[key], "__DELETE__", localSyncKey, true)
	delete(m.totalRecharges, key)
}

func (m *MModelActivity) ClearTotalRecharges() {
	for k := range m.totalRecharges {
		m.RemoveTotalRecharges(k)
	}
}

func (m *MModelActivity) GetTotalRechargesCount() int64 {
	return int64(len(m.totalRecharges))
}

// 限时累计充值活动 活动id => TimeLimitTotalRechargeInfo
// 累计金额、天数
func (m *MModelActivity) RangeTotalRecharges(f func(key int64, value *datas.MTimeLimitTotalRechargeInfo) bool) {
	for k, v := range m.totalRecharges {
		if !f(k, v) {
			return
		}
	}
}

// 冲榜活动信息
func (m *MModelActivity) GetSawingData() *MSawingInfo {
	return m.sawingData
}

func (m *MModelActivity) SetSawingData(value *MSawingInfo) {
	syncKey := m.selfSyncID + "sawing_data"
	if m.checkDirty(m.sawingData, value, syncKey, true) {
		value.SetCollector(syncKey, m.collector, m.changedCb)
	}
	m.sawingData = value
}

type MSawingInfo struct {
	// 冲榜活动轮次
	sawingRound int64
	// 冲榜活动轮次阶段
	sawingStep int64
	status     datas.ActivityStatus

	// 自己本身的同步key,由父对象指定
	selfSyncID string
	// 收集字典,每帧清空同步
	collector delta.ICollector
	// 监测变化回调
	changedCb func(string)
}

// 构造函数
func NewMSawingInfo() *MSawingInfo {
	m := &MSawingInfo{}
	return m
}

// PB构造函数
func NewPBSawingInfo() *PBSawingInfo {
	pb := &PBSawingInfo{}
	return pb
}

// 设置collector函数
func (m *MSawingInfo) SetCollector(syncID string, collector delta.ICollector, cb func(string)) {
	m.collector = collector
	m.changedCb = cb
	if syncID != "" {
		syncID = syncID + "."
	}
	m.selfSyncID = syncID
}

// 检查数值变化函数
func (m *MSawingInfo) checkDirty(valueOld any, valueNew any, key string, ntfClient bool) bool {
	if reflect.DeepEqual(valueOld, valueNew) {
		return false
	}
	if m.collector != nil {
		m.collector.Collect(key, valueNew, ntfClient)
	}
	if m.changedCb != nil {
		m.changedCb(key)
	}
	return true
}

// ToPB函数
func (m *MSawingInfo) ToPB() *PBSawingInfo {
	if m == nil {
		return nil
	}
	pb := NewPBSawingInfo()
	pb.SawingRound = m.sawingRound
	pb.SawingStep = m.sawingStep
	pb.Status = m.status
	return pb
}

// InitFromPB函数
func (m *MSawingInfo) InitFromPB(pb *PBSawingInfo) {
	if pb == nil {
		return
	}
	m.sawingRound = pb.SawingRound
	m.sawingStep = pb.SawingStep
	m.status = pb.Status
}

// String 函数
func (m *MSawingInfo) String() string {
	var strBuilder strings.Builder
	strBuilder.WriteString("{")
	strBuilder.WriteString("sawingRound:")
	fmt.Fprintf(&strBuilder, "%v", m.sawingRound)
	strBuilder.WriteString(", ")
	strBuilder.WriteString("sawingStep:")
	fmt.Fprintf(&strBuilder, "%v", m.sawingStep)
	strBuilder.WriteString(", ")
	strBuilder.WriteString("status:")
	fmt.Fprintf(&strBuilder, "%v", m.status)
	strBuilder.WriteString("}")
	return strBuilder.String()
}

// 冲榜活动轮次
func (m *MSawingInfo) GetSawingRound() int64 {
	return m.sawingRound
}

func (m *MSawingInfo) SetSawingRound(value int64) {
	m.checkDirty(m.sawingRound, value, m.selfSyncID+"sawing_round", true)
	m.sawingRound = value
}

func (m *MSawingInfo) AddSawingRound(add int64) int64 {
	oldValue := m.sawingRound
	m.sawingRound += add
	m.checkDirty(oldValue, m.sawingRound, m.selfSyncID+"sawing_round", true)
	return m.sawingRound
}

// 冲榜活动轮次阶段
func (m *MSawingInfo) GetSawingStep() int64 {
	return m.sawingStep
}

func (m *MSawingInfo) SetSawingStep(value int64) {
	m.checkDirty(m.sawingStep, value, m.selfSyncID+"sawing_step", true)
	m.sawingStep = value
}

func (m *MSawingInfo) AddSawingStep(add int64) int64 {
	oldValue := m.sawingStep
	m.sawingStep += add
	m.checkDirty(oldValue, m.sawingStep, m.selfSyncID+"sawing_step", true)
	return m.sawingStep
}

func (m *MSawingInfo) GetStatus() datas.ActivityStatus {
	return m.status
}

func (m *MSawingInfo) SetStatus(value datas.ActivityStatus) {
	m.checkDirty(m.status, value, m.selfSyncID+"status", true)
	m.status = value
}
