// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: model/player_model.proto

package model

import (
	_ "github.com/fixkme/protoc-gen-gom/example/pbout/go/pbext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @model
// 玩家数据
type PBPlayerModel struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PlayerId int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// 活动信息
	ModelActivity  *PBModelActivity            `protobuf:"bytes,2,opt,name=model_activity,json=modelActivity,proto3" json:"model_activity,omitempty"`
	ModelActivity2 map[string]*PBModelActivity `protobuf:"bytes,3,rep,name=model_activity2,json=modelActivity2,proto3" json:"model_activity2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PBPlayerModel) Reset() {
	*x = PBPlayerModel{}
	mi := &file_model_player_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBPlayerModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPlayerModel) ProtoMessage() {}

func (x *PBPlayerModel) ProtoReflect() protoreflect.Message {
	mi := &file_model_player_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPlayerModel.ProtoReflect.Descriptor instead.
func (*PBPlayerModel) Descriptor() ([]byte, []int) {
	return file_model_player_model_proto_rawDescGZIP(), []int{0}
}

func (x *PBPlayerModel) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PBPlayerModel) GetModelActivity() *PBModelActivity {
	if x != nil {
		return x.ModelActivity
	}
	return nil
}

func (x *PBPlayerModel) GetModelActivity2() map[string]*PBModelActivity {
	if x != nil {
		return x.ModelActivity2
	}
	return nil
}

var File_model_player_model_proto protoreflect.FileDescriptor

const file_model_player_model_proto_rawDesc = "" +
	"\n" +
	"\x18model/player_model.proto\x12\x05model\x1a\x1amodel/model_activity.proto\x1a\x17pbext/options_ext.proto\"\x9d\x02\n" +
	"\vPlayerModel\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12;\n" +
	"\x0emodel_activity\x18\x02 \x01(\v2\x14.model.ModelActivityR\rmodelActivity\x12U\n" +
	"\x0fmodel_activity2\x18\x03 \x03(\v2&.model.PlayerModel.ModelActivity2EntryB\x04\x80\xb5\x18\x01R\x0emodelActivity2\x1aW\n" +
	"\x13ModelActivity2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.model.ModelActivityR\x05value:\x028\x01:\x04\x80\xb5\x18\x01BDZ7github.com/fixkme/protoc-gen-gom/example/pbout/go/model\xaa\x02\bProtocolb\x06proto3"

var (
	file_model_player_model_proto_rawDescOnce sync.Once
	file_model_player_model_proto_rawDescData []byte
)

func file_model_player_model_proto_rawDescGZIP() []byte {
	file_model_player_model_proto_rawDescOnce.Do(func() {
		file_model_player_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_player_model_proto_rawDesc), len(file_model_player_model_proto_rawDesc)))
	})
	return file_model_player_model_proto_rawDescData
}

var file_model_player_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_player_model_proto_goTypes = []any{
	(*PBPlayerModel)(nil),   // 0: model.PlayerModel
	nil,                     // 1: model.PlayerModel.ModelActivity2Entry
	(*PBModelActivity)(nil), // 2: model.ModelActivity
}
var file_model_player_model_proto_depIdxs = []int32{
	2, // 0: model.PlayerModel.model_activity:type_name -> model.ModelActivity
	1, // 1: model.PlayerModel.model_activity2:type_name -> model.PlayerModel.ModelActivity2Entry
	2, // 2: model.PlayerModel.ModelActivity2Entry.value:type_name -> model.ModelActivity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_player_model_proto_init() }
func file_model_player_model_proto_init() {
	if File_model_player_model_proto != nil {
		return
	}
	file_model_model_activity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_player_model_proto_rawDesc), len(file_model_player_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_player_model_proto_goTypes,
		DependencyIndexes: file_model_player_model_proto_depIdxs,
		MessageInfos:      file_model_player_model_proto_msgTypes,
	}.Build()
	File_model_player_model_proto = out.File
	file_model_player_model_proto_goTypes = nil
	file_model_player_model_proto_depIdxs = nil
}
