// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.0.0
// 	protoc        v5.27.1
// source: model/player_model.proto

package model

import (
	fmt "fmt"
	delta "github.com/fixkme/gokit/db/mongo/delta"
	reflect "reflect"
	strings "strings"
)

// @model
// 玩家数据
type MPlayerModel struct {
	playerId int64
	// 活动信息
	modelActivity  *MModelActivity
	modelActivity2 map[string]*MModelActivity

	// 自己本身的同步key,由父对象指定
	selfSyncID string
	// 本对象所有属性的同步key数组
	fieldSyncIDs [3]string
	// 收集字典,每帧清空同步
	collector delta.ICollector
	// 监测变化回调
	changedCb func(string)
}

// 构造函数
func NewMPlayerModel() *MPlayerModel {
	m := &MPlayerModel{}
	m.modelActivity = NewMModelActivity()
	m.modelActivity2 = make(map[string]*MModelActivity)
	m.fieldSyncIDs[0] = "player_id"
	m.fieldSyncIDs[1] = "model_activity"
	m.fieldSyncIDs[2] = "model_activity2"
	return m
}

// PB构造函数
func NewPBPlayerModel() *PBPlayerModel {
	pb := &PBPlayerModel{}
	pb.ModelActivity = NewPBModelActivity()
	pb.ModelActivity2 = make(map[string]*PBModelActivity)
	return pb
}

// 设置collector函数
func (m *MPlayerModel) SetCollector(syncID string, collector delta.ICollector, cb func(string)) {
	m.selfSyncID = syncID
	m.collector = collector
	m.changedCb = cb
	if syncID != "" {
		syncID = syncID + "."
	}
	m.fieldSyncIDs[0] = syncID + "player_id"
	m.fieldSyncIDs[1] = syncID + "model_activity"
	m.fieldSyncIDs[2] = syncID + "model_activity2"
	m.modelActivity.SetCollector(m.fieldSyncIDs[1], collector, cb)
	for key, value := range m.modelActivity2 {
		syncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[2], key)
		value.SetCollector(syncKey, collector, cb)
	}
}

// 检查数值变化函数
func (m *MPlayerModel) checkDirty(valueOld any, valueNew any, key string, ntfClient bool) bool {
	if reflect.DeepEqual(valueOld, valueNew) {
		return false
	}
	if m.collector != nil {
		m.collector.Collect(key, valueNew, ntfClient)
	}
	if m.changedCb != nil {
		m.changedCb(key)
	}
	return true
}

// ToPB函数
func (m *MPlayerModel) ToPB() *PBPlayerModel {
	if m == nil {
		return nil
	}
	pb := NewPBPlayerModel()
	pb.PlayerId = m.playerId
	pb.ModelActivity = m.modelActivity.ToPB()
	for key, value := range m.modelActivity2 {
		pb.ModelActivity2[key] = value.ToPB()
	}
	return pb
}

// InitFromPB函数
func (m *MPlayerModel) InitFromPB(pb *PBPlayerModel) {
	if pb == nil {
		return
	}
	m.playerId = pb.PlayerId
	m.modelActivity.InitFromPB(pb.ModelActivity)
	for key, value := range pb.ModelActivity2 {
		v := NewMModelActivity()
		v.InitFromPB(value)
		m.modelActivity2[key] = v
	}
}

// String 函数
func (m *MPlayerModel) String() string {
	var strBuilder strings.Builder
	strBuilder.WriteString("{")
	strBuilder.WriteString("playerId:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.playerId))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("modelActivity:")
	strBuilder.WriteString(m.modelActivity.String())
	strBuilder.WriteString(", ")
	strBuilder.WriteString("modelActivity2:")
	strBuilder.WriteString("{")
	for key, value := range m.modelActivity2 {
		strBuilder.WriteString(fmt.Sprintf("%v:%s ", key, value.String()))
	}
	strBuilder.WriteString("}")
	strBuilder.WriteString("}")
	return strBuilder.String()
}

func (m *MPlayerModel) GetPlayerId() int64 {
	return m.playerId
}

func (m *MPlayerModel) SetPlayerId(value int64) {
	m.checkDirty(m.playerId, value, m.fieldSyncIDs[0], true)
	m.playerId = value
}

func (m *MPlayerModel) AddPlayerId(add int64) int64 {
	oldValue := m.playerId
	m.playerId += add
	m.checkDirty(oldValue, m.playerId, m.fieldSyncIDs[0], true)
	return m.playerId
}

// 活动信息
func (m *MPlayerModel) GetModelActivity() *MModelActivity {
	return m.modelActivity
}

func (m *MPlayerModel) SetModelActivity(value *MModelActivity) {
	if m.checkDirty(m.modelActivity, value, m.fieldSyncIDs[1], true) {
		value.SetCollector(m.fieldSyncIDs[1], m.collector, m.changedCb)
	}
	m.modelActivity = value
}

func (m *MPlayerModel) GetModelActivity2(key string) (*MModelActivity, bool) {
	value, exists := m.modelActivity2[key]
	return value, exists
}

func (m *MPlayerModel) SetModelActivity2(key string, value *MModelActivity) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[2], key)
	var oldValue any
	if v, ok := m.modelActivity2[key]; ok {
		oldValue = v
	} else {
		oldValue = nil
	}
	if m.checkDirty(oldValue, value, localSyncKey, true) {
		value.SetCollector(localSyncKey, m.collector, m.changedCb)
	}
	m.modelActivity2[key] = value
}

func (m *MPlayerModel) RemoveModelActivity2(key string) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[2], key)
	m.checkDirty(m.modelActivity2[key], "__DELETE__", localSyncKey, true)
	delete(m.modelActivity2, key)
}

func (m *MPlayerModel) ClearModelActivity2() {
	for k := range m.modelActivity2 {
		m.RemoveModelActivity2(k)
	}
}

func (m *MPlayerModel) GetModelActivity2Count() int64 {
	return int64(len(m.modelActivity2))
}

func (m *MPlayerModel) RangeModelActivity2(f func(key string, value *MModelActivity) bool) {
	for k, v := range m.modelActivity2 {
		if !f(k, v) {
			return
		}
	}
}
