// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.0.0
// 	protoc        v5.27.1
// source: datas/activity_data.proto

package datas

import (
	fmt "fmt"
	delta "github.com/fixkme/gokit/db/mongo/delta"
	reflect "reflect"
	strings "strings"
)

// 限时 累积充值玩家信息
type MTimeLimitTotalRechargeInfo struct {
	// 活动id
	activityId int64
	// 用户分组
	userGroup int64
	// 累积充值
	totalRecharge int64
	// 已领取奖励列表
	getRewards map[int64]bool
	// 是否处理了结束，如发邮件
	isOver bool
	// 今日是否充值
	dailyFlag bool
	// 累积充值天数
	totalDay int64
	// 上次跨天
	lastResetTime int64

	// 自己本身的同步key,由父对象指定
	selfSyncID string
	// 本对象所有属性的同步key数组
	fieldSyncIDs [8]string
	// 收集字典,每帧清空同步
	collector delta.ICollector
	// 监测变化回调
	changedCb func(string)
}

// 构造函数
func NewMTimeLimitTotalRechargeInfo() *MTimeLimitTotalRechargeInfo {
	m := &MTimeLimitTotalRechargeInfo{}
	m.getRewards = make(map[int64]bool)
	m.fieldSyncIDs[0] = "activity_id"
	m.fieldSyncIDs[1] = "user_group"
	m.fieldSyncIDs[2] = "total_recharge"
	m.fieldSyncIDs[3] = "get_rewards"
	m.fieldSyncIDs[4] = "is_over"
	m.fieldSyncIDs[5] = "daily_flag"
	m.fieldSyncIDs[6] = "total_day"
	m.fieldSyncIDs[7] = "last_reset_time"
	return m
}

// PB构造函数
func NewPBTimeLimitTotalRechargeInfo() *PBTimeLimitTotalRechargeInfo {
	pb := &PBTimeLimitTotalRechargeInfo{}
	pb.GetRewards = make(map[int64]bool)
	return pb
}

// 设置collector函数
func (m *MTimeLimitTotalRechargeInfo) SetCollector(syncID string, collector delta.ICollector, cb func(string)) {
	m.selfSyncID = syncID
	m.collector = collector
	m.changedCb = cb
	if syncID != "" {
		syncID = syncID + "."
	}
	m.fieldSyncIDs[0] = syncID + "activity_id"
	m.fieldSyncIDs[1] = syncID + "user_group"
	m.fieldSyncIDs[2] = syncID + "total_recharge"
	m.fieldSyncIDs[3] = syncID + "get_rewards"
	m.fieldSyncIDs[4] = syncID + "is_over"
	m.fieldSyncIDs[5] = syncID + "daily_flag"
	m.fieldSyncIDs[6] = syncID + "total_day"
	m.fieldSyncIDs[7] = syncID + "last_reset_time"
}

// 检查数值变化函数
func (m *MTimeLimitTotalRechargeInfo) checkDirty(valueOld any, valueNew any, key string, ntfClient bool) bool {
	if reflect.DeepEqual(valueOld, valueNew) {
		return false
	}
	if m.collector != nil {
		m.collector.Collect(key, valueNew, ntfClient)
	}
	if m.changedCb != nil {
		m.changedCb(key)
	}
	return true
}

// ToPB函数
func (m *MTimeLimitTotalRechargeInfo) ToPB() *PBTimeLimitTotalRechargeInfo {
	if m == nil {
		return nil
	}
	pb := NewPBTimeLimitTotalRechargeInfo()
	pb.ActivityId = m.activityId
	pb.UserGroup = m.userGroup
	pb.TotalRecharge = m.totalRecharge
	for key, value := range m.getRewards {
		pb.GetRewards[key] = value
	}
	pb.IsOver = m.isOver
	pb.DailyFlag = m.dailyFlag
	pb.TotalDay = m.totalDay
	pb.LastResetTime = m.lastResetTime
	return pb
}

// InitFromPB函数
func (m *MTimeLimitTotalRechargeInfo) InitFromPB(pb *PBTimeLimitTotalRechargeInfo) {
	if pb == nil {
		return
	}
	m.activityId = pb.ActivityId
	m.userGroup = pb.UserGroup
	m.totalRecharge = pb.TotalRecharge
	if pb.GetRewards != nil {
		m.getRewards = pb.GetRewards
	}
	m.isOver = pb.IsOver
	m.dailyFlag = pb.DailyFlag
	m.totalDay = pb.TotalDay
	m.lastResetTime = pb.LastResetTime
}

// String 函数
func (m *MTimeLimitTotalRechargeInfo) String() string {
	var strBuilder strings.Builder
	strBuilder.WriteString("{")
	strBuilder.WriteString("activityId:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.activityId))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("userGroup:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.userGroup))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("totalRecharge:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.totalRecharge))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("getRewards:")
	strBuilder.WriteString("{")
	for key, value := range m.getRewards {
		strBuilder.WriteString(fmt.Sprintf("%v:%v ", key, value))
	}
	strBuilder.WriteString("}")
	strBuilder.WriteString(", ")
	strBuilder.WriteString("isOver:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.isOver))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("dailyFlag:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.dailyFlag))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("totalDay:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.totalDay))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("lastResetTime:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.lastResetTime))
	strBuilder.WriteString("}")
	return strBuilder.String()
}

// 活动id
func (m *MTimeLimitTotalRechargeInfo) GetActivityId() int64 {
	return m.activityId
}

func (m *MTimeLimitTotalRechargeInfo) SetActivityId(value int64) {
	m.checkDirty(m.activityId, value, m.fieldSyncIDs[0], true)
	m.activityId = value
}

func (m *MTimeLimitTotalRechargeInfo) AddActivityId(add int64) int64 {
	oldValue := m.activityId
	m.activityId += add
	m.checkDirty(oldValue, m.activityId, m.fieldSyncIDs[0], true)
	return m.activityId
}

// 用户分组
func (m *MTimeLimitTotalRechargeInfo) GetUserGroup() int64 {
	return m.userGroup
}

func (m *MTimeLimitTotalRechargeInfo) SetUserGroup(value int64) {
	m.checkDirty(m.userGroup, value, m.fieldSyncIDs[1], true)
	m.userGroup = value
}

func (m *MTimeLimitTotalRechargeInfo) AddUserGroup(add int64) int64 {
	oldValue := m.userGroup
	m.userGroup += add
	m.checkDirty(oldValue, m.userGroup, m.fieldSyncIDs[1], true)
	return m.userGroup
}

// 累积充值
func (m *MTimeLimitTotalRechargeInfo) GetTotalRecharge() int64 {
	return m.totalRecharge
}

func (m *MTimeLimitTotalRechargeInfo) SetTotalRecharge(value int64) {
	m.checkDirty(m.totalRecharge, value, m.fieldSyncIDs[2], true)
	m.totalRecharge = value
}

func (m *MTimeLimitTotalRechargeInfo) AddTotalRecharge(add int64) int64 {
	oldValue := m.totalRecharge
	m.totalRecharge += add
	m.checkDirty(oldValue, m.totalRecharge, m.fieldSyncIDs[2], true)
	return m.totalRecharge
}

// 已领取奖励列表
func (m *MTimeLimitTotalRechargeInfo) GetGetRewards(key int64) (bool, bool) {
	value, exists := m.getRewards[key]
	return value, exists
}

func (m *MTimeLimitTotalRechargeInfo) SetGetRewards(key int64, value bool) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[3], key)
	var oldValue any
	if v, ok := m.getRewards[key]; ok {
		oldValue = v
	} else {
		oldValue = nil
	}
	m.checkDirty(oldValue, value, localSyncKey, true)
	m.getRewards[key] = value
}

func (m *MTimeLimitTotalRechargeInfo) RemoveGetRewards(key int64) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[3], key)
	m.checkDirty(m.getRewards[key], "__DELETE__", localSyncKey, true)
	delete(m.getRewards, key)
}

func (m *MTimeLimitTotalRechargeInfo) ClearGetRewards() {
	for k := range m.getRewards {
		m.RemoveGetRewards(k)
	}
}

func (m *MTimeLimitTotalRechargeInfo) GetGetRewardsCount() int64 {
	return int64(len(m.getRewards))
}

// 已领取奖励列表
func (m *MTimeLimitTotalRechargeInfo) RangeGetRewards(f func(key int64, value bool) bool) {
	for k, v := range m.getRewards {
		if !f(k, v) {
			return
		}
	}
}

// 是否处理了结束，如发邮件
func (m *MTimeLimitTotalRechargeInfo) GetIsOver() bool {
	return m.isOver
}

func (m *MTimeLimitTotalRechargeInfo) SetIsOver(value bool) {
	m.checkDirty(m.isOver, value, m.fieldSyncIDs[4], true)
	m.isOver = value
}

// 今日是否充值
func (m *MTimeLimitTotalRechargeInfo) GetDailyFlag() bool {
	return m.dailyFlag
}

func (m *MTimeLimitTotalRechargeInfo) SetDailyFlag(value bool) {
	m.checkDirty(m.dailyFlag, value, m.fieldSyncIDs[5], true)
	m.dailyFlag = value
}

// 累积充值天数
func (m *MTimeLimitTotalRechargeInfo) GetTotalDay() int64 {
	return m.totalDay
}

func (m *MTimeLimitTotalRechargeInfo) SetTotalDay(value int64) {
	m.checkDirty(m.totalDay, value, m.fieldSyncIDs[6], true)
	m.totalDay = value
}

func (m *MTimeLimitTotalRechargeInfo) AddTotalDay(add int64) int64 {
	oldValue := m.totalDay
	m.totalDay += add
	m.checkDirty(oldValue, m.totalDay, m.fieldSyncIDs[6], true)
	return m.totalDay
}

// 上次跨天
func (m *MTimeLimitTotalRechargeInfo) GetLastResetTime() int64 {
	return m.lastResetTime
}

func (m *MTimeLimitTotalRechargeInfo) SetLastResetTime(value int64) {
	m.checkDirty(m.lastResetTime, value, m.fieldSyncIDs[7], true)
	m.lastResetTime = value
}

func (m *MTimeLimitTotalRechargeInfo) AddLastResetTime(add int64) int64 {
	oldValue := m.lastResetTime
	m.lastResetTime += add
	m.checkDirty(oldValue, m.lastResetTime, m.fieldSyncIDs[7], true)
	return m.lastResetTime
}
