// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: datas/activity_data_ss.proto

package datas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器用的活动信息
// 只用于服务器数据库
type PBActivityData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动id
	ActivityId int64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 唯一id
	// 功能类型
	FuncType ActivityType `protobuf:"varint,2,opt,name=func_type,json=funcType,proto3,enum=datas.ActivityType" json:"func_type,omitempty"`
	// 活动状态
	Status ActivityStatus `protobuf:"varint,3,opt,name=status,proto3,enum=datas.ActivityStatus" json:"status,omitempty"`
	// 显示开始时间
	ShowStart int64 `protobuf:"varint,4,opt,name=show_start,json=showStart,proto3" json:"show_start,omitempty"`
	// 显示结束时间，结束之前还能领奖
	ShowEnd int64 `protobuf:"varint,5,opt,name=show_end,json=showEnd,proto3" json:"show_end,omitempty"`
	// 生效开始时间，可以做任务了
	EffectStart int64 `protobuf:"varint,6,opt,name=effect_start,json=effectStart,proto3" json:"effect_start,omitempty"`
	// 生效结束时间，不能做任务
	EffectEnd int64 `protobuf:"varint,7,opt,name=effect_end,json=effectEnd,proto3" json:"effect_end,omitempty"`
	// 配置模板
	ConfigTemp int64 `protobuf:"varint,8,opt,name=config_temp,json=configTemp,proto3" json:"config_temp,omitempty"`
	// 配置内容 json 废弃
	ConfigContent string `protobuf:"bytes,9,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	// 配置结构名，前端用来解析config_content 废弃
	ConfigName string `protobuf:"bytes,10,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	// 有效的服务器id，-1表示全部服务器
	ServerIncludes []int64 `protobuf:"varint,11,rep,packed,name=server_includes,json=serverIncludes,proto3" json:"server_includes,omitempty"`
	// 排除的服务器id
	ServerExcludes []int64 `protobuf:"varint,12,rep,packed,name=server_excludes,json=serverExcludes,proto3" json:"server_excludes,omitempty"`
	// 服务器分组列表
	ServerGroups []*PBActivityServerGroup `protobuf:"bytes,13,rep,name=server_groups,json=serverGroups,proto3" json:"server_groups,omitempty"`
	// 来源 0后台 1本地配置
	SrcType       int64 `protobuf:"varint,14,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBActivityData) Reset() {
	*x = PBActivityData{}
	mi := &file_datas_activity_data_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBActivityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBActivityData) ProtoMessage() {}

func (x *PBActivityData) ProtoReflect() protoreflect.Message {
	mi := &file_datas_activity_data_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBActivityData.ProtoReflect.Descriptor instead.
func (*PBActivityData) Descriptor() ([]byte, []int) {
	return file_datas_activity_data_ss_proto_rawDescGZIP(), []int{0}
}

func (x *PBActivityData) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PBActivityData) GetFuncType() ActivityType {
	if x != nil {
		return x.FuncType
	}
	return ActivityType_Unknown
}

func (x *PBActivityData) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_New
}

func (x *PBActivityData) GetShowStart() int64 {
	if x != nil {
		return x.ShowStart
	}
	return 0
}

func (x *PBActivityData) GetShowEnd() int64 {
	if x != nil {
		return x.ShowEnd
	}
	return 0
}

func (x *PBActivityData) GetEffectStart() int64 {
	if x != nil {
		return x.EffectStart
	}
	return 0
}

func (x *PBActivityData) GetEffectEnd() int64 {
	if x != nil {
		return x.EffectEnd
	}
	return 0
}

func (x *PBActivityData) GetConfigTemp() int64 {
	if x != nil {
		return x.ConfigTemp
	}
	return 0
}

func (x *PBActivityData) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *PBActivityData) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *PBActivityData) GetServerIncludes() []int64 {
	if x != nil {
		return x.ServerIncludes
	}
	return nil
}

func (x *PBActivityData) GetServerExcludes() []int64 {
	if x != nil {
		return x.ServerExcludes
	}
	return nil
}

func (x *PBActivityData) GetServerGroups() []*PBActivityServerGroup {
	if x != nil {
		return x.ServerGroups
	}
	return nil
}

func (x *PBActivityData) GetSrcType() int64 {
	if x != nil {
		return x.SrcType
	}
	return 0
}

var File_datas_activity_data_ss_proto protoreflect.FileDescriptor

const file_datas_activity_data_ss_proto_rawDesc = "" +
	"\n" +
	"\x1cdatas/activity_data_ss.proto\x12\x05datas\x1a\x19datas/activity_data.proto\"\xa3\x04\n" +
	"\fActivityData\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x120\n" +
	"\tfunc_type\x18\x02 \x01(\x0e2\x13.datas.ActivityTypeR\bfuncType\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.datas.ActivityStatusR\x06status\x12\x1d\n" +
	"\n" +
	"show_start\x18\x04 \x01(\x03R\tshowStart\x12\x19\n" +
	"\bshow_end\x18\x05 \x01(\x03R\ashowEnd\x12!\n" +
	"\feffect_start\x18\x06 \x01(\x03R\veffectStart\x12\x1d\n" +
	"\n" +
	"effect_end\x18\a \x01(\x03R\teffectEnd\x12\x1f\n" +
	"\vconfig_temp\x18\b \x01(\x03R\n" +
	"configTemp\x12%\n" +
	"\x0econfig_content\x18\t \x01(\tR\rconfigContent\x12\x1f\n" +
	"\vconfig_name\x18\n" +
	" \x01(\tR\n" +
	"configName\x12'\n" +
	"\x0fserver_includes\x18\v \x03(\x03R\x0eserverIncludes\x12'\n" +
	"\x0fserver_excludes\x18\f \x03(\x03R\x0eserverExcludes\x12?\n" +
	"\rserver_groups\x18\r \x03(\v2\x1a.datas.ActivityServerGroupR\fserverGroups\x12\x19\n" +
	"\bsrc_type\x18\x0e \x01(\x03R\asrcTypeBDZ7github.com/fixkme/protoc-gen-gom/example/pbout/go/datas\xaa\x02\bProtocolb\x06proto3"

var (
	file_datas_activity_data_ss_proto_rawDescOnce sync.Once
	file_datas_activity_data_ss_proto_rawDescData []byte
)

func file_datas_activity_data_ss_proto_rawDescGZIP() []byte {
	file_datas_activity_data_ss_proto_rawDescOnce.Do(func() {
		file_datas_activity_data_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datas_activity_data_ss_proto_rawDesc), len(file_datas_activity_data_ss_proto_rawDesc)))
	})
	return file_datas_activity_data_ss_proto_rawDescData
}

var file_datas_activity_data_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_datas_activity_data_ss_proto_goTypes = []any{
	(*PBActivityData)(nil),        // 0: datas.ActivityData
	(ActivityType)(0),             // 1: datas.ActivityType
	(ActivityStatus)(0),           // 2: datas.ActivityStatus
	(*PBActivityServerGroup)(nil), // 3: datas.ActivityServerGroup
}
var file_datas_activity_data_ss_proto_depIdxs = []int32{
	1, // 0: datas.ActivityData.func_type:type_name -> datas.ActivityType
	2, // 1: datas.ActivityData.status:type_name -> datas.ActivityStatus
	3, // 2: datas.ActivityData.server_groups:type_name -> datas.ActivityServerGroup
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_datas_activity_data_ss_proto_init() }
func file_datas_activity_data_ss_proto_init() {
	if File_datas_activity_data_ss_proto != nil {
		return
	}
	file_datas_activity_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datas_activity_data_ss_proto_rawDesc), len(file_datas_activity_data_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datas_activity_data_ss_proto_goTypes,
		DependencyIndexes: file_datas_activity_data_ss_proto_depIdxs,
		MessageInfos:      file_datas_activity_data_ss_proto_msgTypes,
	}.Build()
	File_datas_activity_data_ss_proto = out.File
	file_datas_activity_data_ss_proto_goTypes = nil
	file_datas_activity_data_ss_proto_depIdxs = nil
}
