// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: datas/activity_data.proto

package datas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 活动类型
type ActivityType int32

const (
	ActivityType_Unknown       ActivityType = 0
	ActivityType_TotalRecharge ActivityType = 1
	ActivityType_BattlePass    ActivityType = 2
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "Unknown",
		1: "TotalRecharge",
		2: "BattlePass",
	}
	ActivityType_value = map[string]int32{
		"Unknown":       0,
		"TotalRecharge": 1,
		"BattlePass":    2,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_datas_activity_data_proto_enumTypes[0].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_datas_activity_data_proto_enumTypes[0]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_datas_activity_data_proto_rawDescGZIP(), []int{0}
}

// 活动状态
type ActivityStatus int32

const (
	ActivityStatus_New     ActivityStatus = 0
	ActivityStatus_Launch  ActivityStatus = 1
	ActivityStatus_Show    ActivityStatus = 2
	ActivityStatus_Open    ActivityStatus = 3
	ActivityStatus_Close   ActivityStatus = 4
	ActivityStatus_Expired ActivityStatus = 5
	ActivityStatus_Invalid ActivityStatus = 6
)

// Enum value maps for ActivityStatus.
var (
	ActivityStatus_name = map[int32]string{
		0: "New",
		1: "Launch",
		2: "Show",
		3: "Open",
		4: "Close",
		5: "Expired",
		6: "Invalid",
	}
	ActivityStatus_value = map[string]int32{
		"New":     0,
		"Launch":  1,
		"Show":    2,
		"Open":    3,
		"Close":   4,
		"Expired": 5,
		"Invalid": 6,
	}
)

func (x ActivityStatus) Enum() *ActivityStatus {
	p := new(ActivityStatus)
	*p = x
	return p
}

func (x ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_datas_activity_data_proto_enumTypes[1].Descriptor()
}

func (ActivityStatus) Type() protoreflect.EnumType {
	return &file_datas_activity_data_proto_enumTypes[1]
}

func (x ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityStatus.Descriptor instead.
func (ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_datas_activity_data_proto_rawDescGZIP(), []int{1}
}

// 服务器用的活动信息
// 只用于服务器数据库
type PBActivityInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动id
	ActivityId int64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 唯一id
	// 功能类型
	FuncType ActivityType `protobuf:"varint,2,opt,name=func_type,json=funcType,proto3,enum=datas.ActivityType" json:"func_type,omitempty"`
	// 活动状态
	Status ActivityStatus `protobuf:"varint,3,opt,name=status,proto3,enum=datas.ActivityStatus" json:"status,omitempty"`
	// 显示开始时间
	ShowStart int64 `protobuf:"varint,4,opt,name=show_start,json=showStart,proto3" json:"show_start,omitempty"`
	// 显示结束时间，结束之前还能领奖
	ShowEnd int64 `protobuf:"varint,5,opt,name=show_end,json=showEnd,proto3" json:"show_end,omitempty"`
	// 生效开始时间，可以做任务了
	EffectStart int64 `protobuf:"varint,6,opt,name=effect_start,json=effectStart,proto3" json:"effect_start,omitempty"`
	// 生效结束时间，不能做任务
	EffectEnd int64 `protobuf:"varint,7,opt,name=effect_end,json=effectEnd,proto3" json:"effect_end,omitempty"`
	// 配置模板
	ConfigTemp int64 `protobuf:"varint,8,opt,name=config_temp,json=configTemp,proto3" json:"config_temp,omitempty"`
	// 配置内容 json 废弃
	ConfigContent string `protobuf:"bytes,9,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	// 配置结构名，前端用来解析config_content 废弃
	ConfigName string `protobuf:"bytes,10,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	// 有效的服务器id，-1表示全部服务器
	ServerIncludes []int64 `protobuf:"varint,11,rep,packed,name=server_includes,json=serverIncludes,proto3" json:"server_includes,omitempty"`
	// 排除的服务器id
	ServerExcludes []int64 `protobuf:"varint,12,rep,packed,name=server_excludes,json=serverExcludes,proto3" json:"server_excludes,omitempty"`
	// 服务器分组列表
	ServerGroups []*PBActivityServerGroup `protobuf:"bytes,13,rep,name=server_groups,json=serverGroups,proto3" json:"server_groups,omitempty"`
	// 来源 0后台 1本地配置
	SrcType       int64 `protobuf:"varint,14,opt,name=src_type,json=srcType,proto3" json:"src_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBActivityInfo) Reset() {
	*x = PBActivityInfo{}
	mi := &file_datas_activity_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBActivityInfo) ProtoMessage() {}

func (x *PBActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datas_activity_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBActivityInfo.ProtoReflect.Descriptor instead.
func (*PBActivityInfo) Descriptor() ([]byte, []int) {
	return file_datas_activity_data_proto_rawDescGZIP(), []int{0}
}

func (x *PBActivityInfo) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PBActivityInfo) GetFuncType() ActivityType {
	if x != nil {
		return x.FuncType
	}
	return ActivityType_Unknown
}

func (x *PBActivityInfo) GetStatus() ActivityStatus {
	if x != nil {
		return x.Status
	}
	return ActivityStatus_New
}

func (x *PBActivityInfo) GetShowStart() int64 {
	if x != nil {
		return x.ShowStart
	}
	return 0
}

func (x *PBActivityInfo) GetShowEnd() int64 {
	if x != nil {
		return x.ShowEnd
	}
	return 0
}

func (x *PBActivityInfo) GetEffectStart() int64 {
	if x != nil {
		return x.EffectStart
	}
	return 0
}

func (x *PBActivityInfo) GetEffectEnd() int64 {
	if x != nil {
		return x.EffectEnd
	}
	return 0
}

func (x *PBActivityInfo) GetConfigTemp() int64 {
	if x != nil {
		return x.ConfigTemp
	}
	return 0
}

func (x *PBActivityInfo) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *PBActivityInfo) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *PBActivityInfo) GetServerIncludes() []int64 {
	if x != nil {
		return x.ServerIncludes
	}
	return nil
}

func (x *PBActivityInfo) GetServerExcludes() []int64 {
	if x != nil {
		return x.ServerExcludes
	}
	return nil
}

func (x *PBActivityInfo) GetServerGroups() []*PBActivityServerGroup {
	if x != nil {
		return x.ServerGroups
	}
	return nil
}

func (x *PBActivityInfo) GetSrcType() int64 {
	if x != nil {
		return x.SrcType
	}
	return 0
}

// 活动服务器分组
type PBActivityServerGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分组id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 成员列表
	Elems         []int64 `protobuf:"varint,2,rep,packed,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBActivityServerGroup) Reset() {
	*x = PBActivityServerGroup{}
	mi := &file_datas_activity_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBActivityServerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBActivityServerGroup) ProtoMessage() {}

func (x *PBActivityServerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_datas_activity_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBActivityServerGroup.ProtoReflect.Descriptor instead.
func (*PBActivityServerGroup) Descriptor() ([]byte, []int) {
	return file_datas_activity_data_proto_rawDescGZIP(), []int{1}
}

func (x *PBActivityServerGroup) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PBActivityServerGroup) GetElems() []int64 {
	if x != nil {
		return x.Elems
	}
	return nil
}

// 限时 累积充值玩家信息
type PBTimeLimitTotalRechargeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 活动id
	ActivityId int64 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	// 用户分组
	UserGroup int64 `protobuf:"varint,2,opt,name=user_group,json=userGroup,proto3" json:"user_group,omitempty"`
	// 累积充值
	TotalRecharge int64 `protobuf:"varint,3,opt,name=total_recharge,json=totalRecharge,proto3" json:"total_recharge,omitempty"`
	// 已领取奖励列表
	GetRewards map[int64]bool `protobuf:"bytes,4,rep,name=get_rewards,json=getRewards,proto3" json:"get_rewards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 是否处理了结束，如发邮件
	IsOver bool `protobuf:"varint,5,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	// 今日是否充值
	DailyFlag bool `protobuf:"varint,6,opt,name=daily_flag,json=dailyFlag,proto3" json:"daily_flag,omitempty"`
	// 累积充值天数
	TotalDay int64 `protobuf:"varint,7,opt,name=total_day,json=totalDay,proto3" json:"total_day,omitempty"`
	// 上次跨天
	LastResetTime int64 `protobuf:"varint,8,opt,name=last_reset_time,json=lastResetTime,proto3" json:"last_reset_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBTimeLimitTotalRechargeInfo) Reset() {
	*x = PBTimeLimitTotalRechargeInfo{}
	mi := &file_datas_activity_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBTimeLimitTotalRechargeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBTimeLimitTotalRechargeInfo) ProtoMessage() {}

func (x *PBTimeLimitTotalRechargeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_datas_activity_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBTimeLimitTotalRechargeInfo.ProtoReflect.Descriptor instead.
func (*PBTimeLimitTotalRechargeInfo) Descriptor() ([]byte, []int) {
	return file_datas_activity_data_proto_rawDescGZIP(), []int{2}
}

func (x *PBTimeLimitTotalRechargeInfo) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *PBTimeLimitTotalRechargeInfo) GetUserGroup() int64 {
	if x != nil {
		return x.UserGroup
	}
	return 0
}

func (x *PBTimeLimitTotalRechargeInfo) GetTotalRecharge() int64 {
	if x != nil {
		return x.TotalRecharge
	}
	return 0
}

func (x *PBTimeLimitTotalRechargeInfo) GetGetRewards() map[int64]bool {
	if x != nil {
		return x.GetRewards
	}
	return nil
}

func (x *PBTimeLimitTotalRechargeInfo) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

func (x *PBTimeLimitTotalRechargeInfo) GetDailyFlag() bool {
	if x != nil {
		return x.DailyFlag
	}
	return false
}

func (x *PBTimeLimitTotalRechargeInfo) GetTotalDay() int64 {
	if x != nil {
		return x.TotalDay
	}
	return 0
}

func (x *PBTimeLimitTotalRechargeInfo) GetLastResetTime() int64 {
	if x != nil {
		return x.LastResetTime
	}
	return 0
}

var File_datas_activity_data_proto protoreflect.FileDescriptor

const file_datas_activity_data_proto_rawDesc = "" +
	"\n" +
	"\x19datas/activity_data.proto\x12\x05datas\"\xa3\x04\n" +
	"\fActivityInfo\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x120\n" +
	"\tfunc_type\x18\x02 \x01(\x0e2\x13.datas.ActivityTypeR\bfuncType\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.datas.ActivityStatusR\x06status\x12\x1d\n" +
	"\n" +
	"show_start\x18\x04 \x01(\x03R\tshowStart\x12\x19\n" +
	"\bshow_end\x18\x05 \x01(\x03R\ashowEnd\x12!\n" +
	"\feffect_start\x18\x06 \x01(\x03R\veffectStart\x12\x1d\n" +
	"\n" +
	"effect_end\x18\a \x01(\x03R\teffectEnd\x12\x1f\n" +
	"\vconfig_temp\x18\b \x01(\x03R\n" +
	"configTemp\x12%\n" +
	"\x0econfig_content\x18\t \x01(\tR\rconfigContent\x12\x1f\n" +
	"\vconfig_name\x18\n" +
	" \x01(\tR\n" +
	"configName\x12'\n" +
	"\x0fserver_includes\x18\v \x03(\x03R\x0eserverIncludes\x12'\n" +
	"\x0fserver_excludes\x18\f \x03(\x03R\x0eserverExcludes\x12?\n" +
	"\rserver_groups\x18\r \x03(\v2\x1a.datas.ActivityServerGroupR\fserverGroups\x12\x19\n" +
	"\bsrc_type\x18\x0e \x01(\x03R\asrcType\";\n" +
	"\x13ActivityServerGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05elems\x18\x02 \x03(\x03R\x05elems\"\x93\x03\n" +
	"\x1aTimeLimitTotalRechargeInfo\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"user_group\x18\x02 \x01(\x03R\tuserGroup\x12%\n" +
	"\x0etotal_recharge\x18\x03 \x01(\x03R\rtotalRecharge\x12R\n" +
	"\vget_rewards\x18\x04 \x03(\v21.datas.TimeLimitTotalRechargeInfo.GetRewardsEntryR\n" +
	"getRewards\x12\x17\n" +
	"\ais_over\x18\x05 \x01(\bR\x06isOver\x12\x1d\n" +
	"\n" +
	"daily_flag\x18\x06 \x01(\bR\tdailyFlag\x12\x1b\n" +
	"\ttotal_day\x18\a \x01(\x03R\btotalDay\x12&\n" +
	"\x0flast_reset_time\x18\b \x01(\x03R\rlastResetTime\x1a=\n" +
	"\x0fGetRewardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01*>\n" +
	"\fActivityType\x12\v\n" +
	"\aUnknown\x10\x00\x12\x11\n" +
	"\rTotalRecharge\x10\x01\x12\x0e\n" +
	"\n" +
	"BattlePass\x10\x02*^\n" +
	"\x0eActivityStatus\x12\a\n" +
	"\x03New\x10\x00\x12\n" +
	"\n" +
	"\x06Launch\x10\x01\x12\b\n" +
	"\x04Show\x10\x02\x12\b\n" +
	"\x04Open\x10\x03\x12\t\n" +
	"\x05Close\x10\x04\x12\v\n" +
	"\aExpired\x10\x05\x12\v\n" +
	"\aInvalid\x10\x06BDZ7github.com/fixkme/protoc-gen-gom/example/pbout/go/datas\xaa\x02\bProtocolb\x06proto3"

var (
	file_datas_activity_data_proto_rawDescOnce sync.Once
	file_datas_activity_data_proto_rawDescData []byte
)

func file_datas_activity_data_proto_rawDescGZIP() []byte {
	file_datas_activity_data_proto_rawDescOnce.Do(func() {
		file_datas_activity_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datas_activity_data_proto_rawDesc), len(file_datas_activity_data_proto_rawDesc)))
	})
	return file_datas_activity_data_proto_rawDescData
}

var file_datas_activity_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_datas_activity_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_datas_activity_data_proto_goTypes = []any{
	(ActivityType)(0),                    // 0: datas.ActivityType
	(ActivityStatus)(0),                  // 1: datas.ActivityStatus
	(*PBActivityInfo)(nil),               // 2: datas.ActivityInfo
	(*PBActivityServerGroup)(nil),        // 3: datas.ActivityServerGroup
	(*PBTimeLimitTotalRechargeInfo)(nil), // 4: datas.TimeLimitTotalRechargeInfo
	nil,                                  // 5: datas.TimeLimitTotalRechargeInfo.GetRewardsEntry
}
var file_datas_activity_data_proto_depIdxs = []int32{
	0, // 0: datas.ActivityInfo.func_type:type_name -> datas.ActivityType
	1, // 1: datas.ActivityInfo.status:type_name -> datas.ActivityStatus
	3, // 2: datas.ActivityInfo.server_groups:type_name -> datas.ActivityServerGroup
	5, // 3: datas.TimeLimitTotalRechargeInfo.get_rewards:type_name -> datas.TimeLimitTotalRechargeInfo.GetRewardsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_datas_activity_data_proto_init() }
func file_datas_activity_data_proto_init() {
	if File_datas_activity_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datas_activity_data_proto_rawDesc), len(file_datas_activity_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datas_activity_data_proto_goTypes,
		DependencyIndexes: file_datas_activity_data_proto_depIdxs,
		EnumInfos:         file_datas_activity_data_proto_enumTypes,
		MessageInfos:      file_datas_activity_data_proto_msgTypes,
	}.Build()
	File_datas_activity_data_proto = out.File
	file_datas_activity_data_proto_goTypes = nil
	file_datas_activity_data_proto_depIdxs = nil
}
