// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: options_ext.proto

package pbext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "is_model",
		Tag:           "varint,50000,opt,name=is_model",
		Filename:      "options_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "is_code_error",
		Tag:           "varint,50000,opt,name=is_code_error",
		Filename:      "options_ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "no_sync_client",
		Tag:           "varint,50000,opt,name=no_sync_client",
		Filename:      "options_ext.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool is_model = 50000;
	E_IsModel = &file_options_ext_proto_extTypes[0] //告诉插件当前Message为model
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional bool is_code_error = 50000;
	E_IsCodeError = &file_options_ext_proto_extTypes[1] //告诉插件生成CodeError
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool no_sync_client = 50000;
	E_NoSyncClient = &file_options_ext_proto_extTypes[2] //该字段不需要同步给客户端
)

var File_options_ext_proto protoreflect.FileDescriptor

const file_options_ext_proto_rawDesc = "" +
	"\n" +
	"\x11options_ext.proto\x1a google/protobuf/descriptor.proto:<\n" +
	"\bis_model\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\bR\aisModel:B\n" +
	"\ris_code_error\x12\x1c.google.protobuf.EnumOptions\x18І\x03 \x01(\bR\visCodeError:E\n" +
	"\x0eno_sync_client\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\bR\fnoSyncClientB\tZ\a./pbextb\x06proto3"

var file_options_ext_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),    // 1: google.protobuf.EnumOptions
	(*descriptorpb.FieldOptions)(nil),   // 2: google.protobuf.FieldOptions
}
var file_options_ext_proto_depIdxs = []int32{
	0, // 0: is_model:extendee -> google.protobuf.MessageOptions
	1, // 1: is_code_error:extendee -> google.protobuf.EnumOptions
	2, // 2: no_sync_client:extendee -> google.protobuf.FieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_ext_proto_init() }
func file_options_ext_proto_init() {
	if File_options_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_ext_proto_rawDesc), len(file_options_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_options_ext_proto_goTypes,
		DependencyIndexes: file_options_ext_proto_depIdxs,
		ExtensionInfos:    file_options_ext_proto_extTypes,
	}.Build()
	File_options_ext_proto = out.File
	file_options_ext_proto_goTypes = nil
	file_options_ext_proto_depIdxs = nil
}
