// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: cerrs/cerrors.proto

package cerrs

import (
	_ "github.com/fixkme/protoc-gen-gom/example/pbout/go/pbext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @CodeError
// Error codes错误码
type ECode int32

const (
	// ok不是错误
	ECode_OK        ECode = 0 // 默认成功
	ECode_UNKNOWN   ECode = 1 // 未知错误
	ECode_NOT_FOUND ECode = 2 // 未找到
	// 已存在
	ECode_ALREADY_EXISTS_1N ECode = 3
)

// Enum value maps for ECode.
var (
	ECode_name = map[int32]string{
		0: "OK",
		1: "UNKNOWN",
		2: "NOT_FOUND",
		3: "ALREADY_EXISTS_1N",
	}
	ECode_value = map[string]int32{
		"OK":                0,
		"UNKNOWN":           1,
		"NOT_FOUND":         2,
		"ALREADY_EXISTS_1N": 3,
	}
)

func (x ECode) Enum() *ECode {
	p := new(ECode)
	*p = x
	return p
}

func (x ECode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECode) Descriptor() protoreflect.EnumDescriptor {
	return file_cerrs_cerrors_proto_enumTypes[0].Descriptor()
}

func (ECode) Type() protoreflect.EnumType {
	return &file_cerrs_cerrors_proto_enumTypes[0]
}

func (x ECode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ECode.Descriptor instead.
func (ECode) EnumDescriptor() ([]byte, []int) {
	return file_cerrs_cerrors_proto_rawDescGZIP(), []int{0}
}

type GlobalECode int32

const (
	GlobalECode_GE_OK                 GlobalECode = 0 //缺省值
	GlobalECode_GE_UNKNOWN            GlobalECode = 1
	GlobalECode_GE_CONNECTION_REFUSED GlobalECode = 2
)

// Enum value maps for GlobalECode.
var (
	GlobalECode_name = map[int32]string{
		0: "GE_OK",
		1: "GE_UNKNOWN",
		2: "GE_CONNECTION_REFUSED",
	}
	GlobalECode_value = map[string]int32{
		"GE_OK":                 0,
		"GE_UNKNOWN":            1,
		"GE_CONNECTION_REFUSED": 2,
	}
)

func (x GlobalECode) Enum() *GlobalECode {
	p := new(GlobalECode)
	*p = x
	return p
}

func (x GlobalECode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalECode) Descriptor() protoreflect.EnumDescriptor {
	return file_cerrs_cerrors_proto_enumTypes[1].Descriptor()
}

func (GlobalECode) Type() protoreflect.EnumType {
	return &file_cerrs_cerrors_proto_enumTypes[1]
}

func (x GlobalECode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalECode.Descriptor instead.
func (GlobalECode) EnumDescriptor() ([]byte, []int) {
	return file_cerrs_cerrors_proto_rawDescGZIP(), []int{1}
}

var File_cerrs_cerrors_proto protoreflect.FileDescriptor

const file_cerrs_cerrors_proto_rawDesc = "" +
	"\n" +
	"\x13cerrs/cerrors.proto\x12\x05cerrs\x1a\x17pbext/options_ext.proto*B\n" +
	"\x05ECode\x12\x06\n" +
	"\x02OK\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x15\n" +
	"\x11ALREADY_EXISTS_1N\x10\x03*I\n" +
	"\vGlobalECode\x12\t\n" +
	"\x05GE_OK\x10\x00\x12\x0e\n" +
	"\n" +
	"GE_UNKNOWN\x10\x01\x12\x19\n" +
	"\x15GE_CONNECTION_REFUSED\x10\x02\x1a\x04\x80\xb5\x18\x01BDZ7github.com/fixkme/protoc-gen-gom/example/pbout/go/cerrs\xaa\x02\bProtocolb\x06proto3"

var (
	file_cerrs_cerrors_proto_rawDescOnce sync.Once
	file_cerrs_cerrors_proto_rawDescData []byte
)

func file_cerrs_cerrors_proto_rawDescGZIP() []byte {
	file_cerrs_cerrors_proto_rawDescOnce.Do(func() {
		file_cerrs_cerrors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerrs_cerrors_proto_rawDesc), len(file_cerrs_cerrors_proto_rawDesc)))
	})
	return file_cerrs_cerrors_proto_rawDescData
}

var file_cerrs_cerrors_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cerrs_cerrors_proto_goTypes = []any{
	(ECode)(0),       // 0: cerrs.ECode
	(GlobalECode)(0), // 1: cerrs.GlobalECode
}
var file_cerrs_cerrors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cerrs_cerrors_proto_init() }
func file_cerrs_cerrors_proto_init() {
	if File_cerrs_cerrors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerrs_cerrors_proto_rawDesc), len(file_cerrs_cerrors_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerrs_cerrors_proto_goTypes,
		DependencyIndexes: file_cerrs_cerrors_proto_depIdxs,
		EnumInfos:         file_cerrs_cerrors_proto_enumTypes,
	}.Build()
	File_cerrs_cerrors_proto = out.File
	file_cerrs_cerrors_proto_goTypes = nil
	file_cerrs_cerrors_proto_depIdxs = nil
}
