// Code generated by protoc-gen-gom. DO NOT EDIT.
package cerrs

import (
	errs "github.com/fixkme/gokit/errs"
)

// @CodeError
// Error codes错误码
var (
	// ok不是错误
	// 默认成功
	Ok = errs.CreateCodeError(int32(ECode_OK), "OK")
	// 未知错误
	Unknown = errs.CreateCodeError(int32(ECode_UNKNOWN), "UNKNOWN")
	// 未找到
	NotFound = errs.CreateCodeError(int32(ECode_NOT_FOUND), "NOT_FOUND")
	// 已存在
	AlreadyExists1N = errs.CreateCodeError(int32(ECode_ALREADY_EXISTS_1N), "ALREADY_EXISTS_1N")
)

var (
	// 缺省值
	GeOk                = errs.CreateCodeError(int32(GlobalECode_GE_OK), "GE_OK")
	GeUnknown           = errs.CreateCodeError(int32(GlobalECode_GE_UNKNOWN), "GE_UNKNOWN")
	GeConnectionRefused = errs.CreateCodeError(int32(GlobalECode_GE_CONNECTION_REFUSED), "GE_CONNECTION_REFUSED")
)
